/*
 * Gitea API
 * This documentation describes the Gitea API.
 *
 * OpenAPI spec version: 1.26.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.gitea.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.gitea.model.ActionWorkflowRun;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.threeten.bp.OffsetDateTime;

/**
 * ActionArtifact represents a ActionArtifact
 */
@ApiModel(description = "ActionArtifact represents a ActionArtifact")

public class ActionArtifact {
  @SerializedName("archive_download_url")
  private String archiveDownloadUrl = null;

  @SerializedName("created_at")
  private OffsetDateTime createdAt = null;

  @SerializedName("expired")
  private Boolean expired = null;

  @SerializedName("expires_at")
  private OffsetDateTime expiresAt = null;

  @SerializedName("id")
  private Long id = null;

  @SerializedName("name")
  private String name = null;

  @SerializedName("size_in_bytes")
  private Long sizeInBytes = null;

  @SerializedName("updated_at")
  private OffsetDateTime updatedAt = null;

  @SerializedName("url")
  private String url = null;

  @SerializedName("workflow_run")
  private ActionWorkflowRun workflowRun = null;

  public ActionArtifact archiveDownloadUrl(String archiveDownloadUrl) {
    this.archiveDownloadUrl = archiveDownloadUrl;
    return this;
  }

   /**
   * Get archiveDownloadUrl
   * @return archiveDownloadUrl
  **/
  @ApiModelProperty(value = "")
  public String getArchiveDownloadUrl() {
    return archiveDownloadUrl;
  }

  public void setArchiveDownloadUrl(String archiveDownloadUrl) {
    this.archiveDownloadUrl = archiveDownloadUrl;
  }

  public ActionArtifact createdAt(OffsetDateTime createdAt) {
    this.createdAt = createdAt;
    return this;
  }

   /**
   * Get createdAt
   * @return createdAt
  **/
  @ApiModelProperty(value = "")
  public OffsetDateTime getCreatedAt() {
    return createdAt;
  }

  public void setCreatedAt(OffsetDateTime createdAt) {
    this.createdAt = createdAt;
  }

  public ActionArtifact expired(Boolean expired) {
    this.expired = expired;
    return this;
  }

   /**
   * Get expired
   * @return expired
  **/
  @ApiModelProperty(value = "")
  public Boolean isExpired() {
    return expired;
  }

  public void setExpired(Boolean expired) {
    this.expired = expired;
  }

  public ActionArtifact expiresAt(OffsetDateTime expiresAt) {
    this.expiresAt = expiresAt;
    return this;
  }

   /**
   * Get expiresAt
   * @return expiresAt
  **/
  @ApiModelProperty(value = "")
  public OffsetDateTime getExpiresAt() {
    return expiresAt;
  }

  public void setExpiresAt(OffsetDateTime expiresAt) {
    this.expiresAt = expiresAt;
  }

  public ActionArtifact id(Long id) {
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @ApiModelProperty(value = "")
  public Long getId() {
    return id;
  }

  public void setId(Long id) {
    this.id = id;
  }

  public ActionArtifact name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Get name
   * @return name
  **/
  @ApiModelProperty(value = "")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public ActionArtifact sizeInBytes(Long sizeInBytes) {
    this.sizeInBytes = sizeInBytes;
    return this;
  }

   /**
   * Get sizeInBytes
   * @return sizeInBytes
  **/
  @ApiModelProperty(value = "")
  public Long getSizeInBytes() {
    return sizeInBytes;
  }

  public void setSizeInBytes(Long sizeInBytes) {
    this.sizeInBytes = sizeInBytes;
  }

  public ActionArtifact updatedAt(OffsetDateTime updatedAt) {
    this.updatedAt = updatedAt;
    return this;
  }

   /**
   * Get updatedAt
   * @return updatedAt
  **/
  @ApiModelProperty(value = "")
  public OffsetDateTime getUpdatedAt() {
    return updatedAt;
  }

  public void setUpdatedAt(OffsetDateTime updatedAt) {
    this.updatedAt = updatedAt;
  }

  public ActionArtifact url(String url) {
    this.url = url;
    return this;
  }

   /**
   * Get url
   * @return url
  **/
  @ApiModelProperty(value = "")
  public String getUrl() {
    return url;
  }

  public void setUrl(String url) {
    this.url = url;
  }

  public ActionArtifact workflowRun(ActionWorkflowRun workflowRun) {
    this.workflowRun = workflowRun;
    return this;
  }

   /**
   * Get workflowRun
   * @return workflowRun
  **/
  @ApiModelProperty(value = "")
  public ActionWorkflowRun getWorkflowRun() {
    return workflowRun;
  }

  public void setWorkflowRun(ActionWorkflowRun workflowRun) {
    this.workflowRun = workflowRun;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ActionArtifact actionArtifact = (ActionArtifact) o;
    return Objects.equals(this.archiveDownloadUrl, actionArtifact.archiveDownloadUrl) &&
        Objects.equals(this.createdAt, actionArtifact.createdAt) &&
        Objects.equals(this.expired, actionArtifact.expired) &&
        Objects.equals(this.expiresAt, actionArtifact.expiresAt) &&
        Objects.equals(this.id, actionArtifact.id) &&
        Objects.equals(this.name, actionArtifact.name) &&
        Objects.equals(this.sizeInBytes, actionArtifact.sizeInBytes) &&
        Objects.equals(this.updatedAt, actionArtifact.updatedAt) &&
        Objects.equals(this.url, actionArtifact.url) &&
        Objects.equals(this.workflowRun, actionArtifact.workflowRun);
  }

  @Override
  public int hashCode() {
    return Objects.hash(archiveDownloadUrl, createdAt, expired, expiresAt, id, name, sizeInBytes, updatedAt, url, workflowRun);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ActionArtifact {\n");
    
    sb.append("    archiveDownloadUrl: ").append(toIndentedString(archiveDownloadUrl)).append("\n");
    sb.append("    createdAt: ").append(toIndentedString(createdAt)).append("\n");
    sb.append("    expired: ").append(toIndentedString(expired)).append("\n");
    sb.append("    expiresAt: ").append(toIndentedString(expiresAt)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    sizeInBytes: ").append(toIndentedString(sizeInBytes)).append("\n");
    sb.append("    updatedAt: ").append(toIndentedString(updatedAt)).append("\n");
    sb.append("    url: ").append(toIndentedString(url)).append("\n");
    sb.append("    workflowRun: ").append(toIndentedString(workflowRun)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

