/*
 * Gitea API
 * This documentation describes the Gitea API.
 *
 * OpenAPI spec version: 1.24.2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.gitea.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.gitea.model.ActionRunnerLabel;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * ActionRunner represents a Runner
 */
@ApiModel(description = "ActionRunner represents a Runner")

public class ActionRunner {
  @SerializedName("busy")
  private Boolean busy = null;

  @SerializedName("ephemeral")
  private Boolean ephemeral = null;

  @SerializedName("id")
  private Long id = null;

  @SerializedName("labels")
  private List<ActionRunnerLabel> labels = null;

  @SerializedName("name")
  private String name = null;

  @SerializedName("status")
  private String status = null;

  public ActionRunner busy(Boolean busy) {
    this.busy = busy;
    return this;
  }

   /**
   * Get busy
   * @return busy
  **/
  @ApiModelProperty(value = "")
  public Boolean isBusy() {
    return busy;
  }

  public void setBusy(Boolean busy) {
    this.busy = busy;
  }

  public ActionRunner ephemeral(Boolean ephemeral) {
    this.ephemeral = ephemeral;
    return this;
  }

   /**
   * Get ephemeral
   * @return ephemeral
  **/
  @ApiModelProperty(value = "")
  public Boolean isEphemeral() {
    return ephemeral;
  }

  public void setEphemeral(Boolean ephemeral) {
    this.ephemeral = ephemeral;
  }

  public ActionRunner id(Long id) {
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @ApiModelProperty(value = "")
  public Long getId() {
    return id;
  }

  public void setId(Long id) {
    this.id = id;
  }

  public ActionRunner labels(List<ActionRunnerLabel> labels) {
    this.labels = labels;
    return this;
  }

  public ActionRunner addLabelsItem(ActionRunnerLabel labelsItem) {
    if (this.labels == null) {
      this.labels = new ArrayList<ActionRunnerLabel>();
    }
    this.labels.add(labelsItem);
    return this;
  }

   /**
   * Get labels
   * @return labels
  **/
  @ApiModelProperty(value = "")
  public List<ActionRunnerLabel> getLabels() {
    return labels;
  }

  public void setLabels(List<ActionRunnerLabel> labels) {
    this.labels = labels;
  }

  public ActionRunner name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Get name
   * @return name
  **/
  @ApiModelProperty(value = "")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public ActionRunner status(String status) {
    this.status = status;
    return this;
  }

   /**
   * Get status
   * @return status
  **/
  @ApiModelProperty(value = "")
  public String getStatus() {
    return status;
  }

  public void setStatus(String status) {
    this.status = status;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ActionRunner actionRunner = (ActionRunner) o;
    return Objects.equals(this.busy, actionRunner.busy) &&
        Objects.equals(this.ephemeral, actionRunner.ephemeral) &&
        Objects.equals(this.id, actionRunner.id) &&
        Objects.equals(this.labels, actionRunner.labels) &&
        Objects.equals(this.name, actionRunner.name) &&
        Objects.equals(this.status, actionRunner.status);
  }

  @Override
  public int hashCode() {
    return Objects.hash(busy, ephemeral, id, labels, name, status);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ActionRunner {\n");
    
    sb.append("    busy: ").append(toIndentedString(busy)).append("\n");
    sb.append("    ephemeral: ").append(toIndentedString(ephemeral)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    labels: ").append(toIndentedString(labels)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

