/*
 * Gitea API
 * This documentation describes the Gitea API.
 *
 * OpenAPI spec version: 1.25.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.gitea.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.gitea.model.Repository;
import io.gitea.model.User;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.threeten.bp.OffsetDateTime;

/**
 * ActionWorkflowRun represents a WorkflowRun
 */
@ApiModel(description = "ActionWorkflowRun represents a WorkflowRun")

public class ActionWorkflowRun {
  @SerializedName("actor")
  private User actor = null;

  @SerializedName("completed_at")
  private OffsetDateTime completedAt = null;

  @SerializedName("conclusion")
  private String conclusion = null;

  @SerializedName("display_title")
  private String displayTitle = null;

  @SerializedName("event")
  private String event = null;

  @SerializedName("head_branch")
  private String headBranch = null;

  @SerializedName("head_repository")
  private Repository headRepository = null;

  @SerializedName("head_sha")
  private String headSha = null;

  @SerializedName("html_url")
  private String htmlUrl = null;

  @SerializedName("id")
  private Long id = null;

  @SerializedName("path")
  private String path = null;

  @SerializedName("repository")
  private Repository repository = null;

  @SerializedName("repository_id")
  private Long repositoryId = null;

  @SerializedName("run_attempt")
  private Long runAttempt = null;

  @SerializedName("run_number")
  private Long runNumber = null;

  @SerializedName("started_at")
  private OffsetDateTime startedAt = null;

  @SerializedName("status")
  private String status = null;

  @SerializedName("trigger_actor")
  private User triggerActor = null;

  @SerializedName("url")
  private String url = null;

  public ActionWorkflowRun actor(User actor) {
    this.actor = actor;
    return this;
  }

   /**
   * Get actor
   * @return actor
  **/
  @ApiModelProperty(value = "")
  public User getActor() {
    return actor;
  }

  public void setActor(User actor) {
    this.actor = actor;
  }

  public ActionWorkflowRun completedAt(OffsetDateTime completedAt) {
    this.completedAt = completedAt;
    return this;
  }

   /**
   * Get completedAt
   * @return completedAt
  **/
  @ApiModelProperty(value = "")
  public OffsetDateTime getCompletedAt() {
    return completedAt;
  }

  public void setCompletedAt(OffsetDateTime completedAt) {
    this.completedAt = completedAt;
  }

  public ActionWorkflowRun conclusion(String conclusion) {
    this.conclusion = conclusion;
    return this;
  }

   /**
   * Get conclusion
   * @return conclusion
  **/
  @ApiModelProperty(value = "")
  public String getConclusion() {
    return conclusion;
  }

  public void setConclusion(String conclusion) {
    this.conclusion = conclusion;
  }

  public ActionWorkflowRun displayTitle(String displayTitle) {
    this.displayTitle = displayTitle;
    return this;
  }

   /**
   * Get displayTitle
   * @return displayTitle
  **/
  @ApiModelProperty(value = "")
  public String getDisplayTitle() {
    return displayTitle;
  }

  public void setDisplayTitle(String displayTitle) {
    this.displayTitle = displayTitle;
  }

  public ActionWorkflowRun event(String event) {
    this.event = event;
    return this;
  }

   /**
   * Get event
   * @return event
  **/
  @ApiModelProperty(value = "")
  public String getEvent() {
    return event;
  }

  public void setEvent(String event) {
    this.event = event;
  }

  public ActionWorkflowRun headBranch(String headBranch) {
    this.headBranch = headBranch;
    return this;
  }

   /**
   * Get headBranch
   * @return headBranch
  **/
  @ApiModelProperty(value = "")
  public String getHeadBranch() {
    return headBranch;
  }

  public void setHeadBranch(String headBranch) {
    this.headBranch = headBranch;
  }

  public ActionWorkflowRun headRepository(Repository headRepository) {
    this.headRepository = headRepository;
    return this;
  }

   /**
   * Get headRepository
   * @return headRepository
  **/
  @ApiModelProperty(value = "")
  public Repository getHeadRepository() {
    return headRepository;
  }

  public void setHeadRepository(Repository headRepository) {
    this.headRepository = headRepository;
  }

  public ActionWorkflowRun headSha(String headSha) {
    this.headSha = headSha;
    return this;
  }

   /**
   * Get headSha
   * @return headSha
  **/
  @ApiModelProperty(value = "")
  public String getHeadSha() {
    return headSha;
  }

  public void setHeadSha(String headSha) {
    this.headSha = headSha;
  }

  public ActionWorkflowRun htmlUrl(String htmlUrl) {
    this.htmlUrl = htmlUrl;
    return this;
  }

   /**
   * Get htmlUrl
   * @return htmlUrl
  **/
  @ApiModelProperty(value = "")
  public String getHtmlUrl() {
    return htmlUrl;
  }

  public void setHtmlUrl(String htmlUrl) {
    this.htmlUrl = htmlUrl;
  }

  public ActionWorkflowRun id(Long id) {
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @ApiModelProperty(value = "")
  public Long getId() {
    return id;
  }

  public void setId(Long id) {
    this.id = id;
  }

  public ActionWorkflowRun path(String path) {
    this.path = path;
    return this;
  }

   /**
   * Get path
   * @return path
  **/
  @ApiModelProperty(value = "")
  public String getPath() {
    return path;
  }

  public void setPath(String path) {
    this.path = path;
  }

  public ActionWorkflowRun repository(Repository repository) {
    this.repository = repository;
    return this;
  }

   /**
   * Get repository
   * @return repository
  **/
  @ApiModelProperty(value = "")
  public Repository getRepository() {
    return repository;
  }

  public void setRepository(Repository repository) {
    this.repository = repository;
  }

  public ActionWorkflowRun repositoryId(Long repositoryId) {
    this.repositoryId = repositoryId;
    return this;
  }

   /**
   * Get repositoryId
   * @return repositoryId
  **/
  @ApiModelProperty(value = "")
  public Long getRepositoryId() {
    return repositoryId;
  }

  public void setRepositoryId(Long repositoryId) {
    this.repositoryId = repositoryId;
  }

  public ActionWorkflowRun runAttempt(Long runAttempt) {
    this.runAttempt = runAttempt;
    return this;
  }

   /**
   * Get runAttempt
   * @return runAttempt
  **/
  @ApiModelProperty(value = "")
  public Long getRunAttempt() {
    return runAttempt;
  }

  public void setRunAttempt(Long runAttempt) {
    this.runAttempt = runAttempt;
  }

  public ActionWorkflowRun runNumber(Long runNumber) {
    this.runNumber = runNumber;
    return this;
  }

   /**
   * Get runNumber
   * @return runNumber
  **/
  @ApiModelProperty(value = "")
  public Long getRunNumber() {
    return runNumber;
  }

  public void setRunNumber(Long runNumber) {
    this.runNumber = runNumber;
  }

  public ActionWorkflowRun startedAt(OffsetDateTime startedAt) {
    this.startedAt = startedAt;
    return this;
  }

   /**
   * Get startedAt
   * @return startedAt
  **/
  @ApiModelProperty(value = "")
  public OffsetDateTime getStartedAt() {
    return startedAt;
  }

  public void setStartedAt(OffsetDateTime startedAt) {
    this.startedAt = startedAt;
  }

  public ActionWorkflowRun status(String status) {
    this.status = status;
    return this;
  }

   /**
   * Get status
   * @return status
  **/
  @ApiModelProperty(value = "")
  public String getStatus() {
    return status;
  }

  public void setStatus(String status) {
    this.status = status;
  }

  public ActionWorkflowRun triggerActor(User triggerActor) {
    this.triggerActor = triggerActor;
    return this;
  }

   /**
   * Get triggerActor
   * @return triggerActor
  **/
  @ApiModelProperty(value = "")
  public User getTriggerActor() {
    return triggerActor;
  }

  public void setTriggerActor(User triggerActor) {
    this.triggerActor = triggerActor;
  }

  public ActionWorkflowRun url(String url) {
    this.url = url;
    return this;
  }

   /**
   * Get url
   * @return url
  **/
  @ApiModelProperty(value = "")
  public String getUrl() {
    return url;
  }

  public void setUrl(String url) {
    this.url = url;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ActionWorkflowRun actionWorkflowRun = (ActionWorkflowRun) o;
    return Objects.equals(this.actor, actionWorkflowRun.actor) &&
        Objects.equals(this.completedAt, actionWorkflowRun.completedAt) &&
        Objects.equals(this.conclusion, actionWorkflowRun.conclusion) &&
        Objects.equals(this.displayTitle, actionWorkflowRun.displayTitle) &&
        Objects.equals(this.event, actionWorkflowRun.event) &&
        Objects.equals(this.headBranch, actionWorkflowRun.headBranch) &&
        Objects.equals(this.headRepository, actionWorkflowRun.headRepository) &&
        Objects.equals(this.headSha, actionWorkflowRun.headSha) &&
        Objects.equals(this.htmlUrl, actionWorkflowRun.htmlUrl) &&
        Objects.equals(this.id, actionWorkflowRun.id) &&
        Objects.equals(this.path, actionWorkflowRun.path) &&
        Objects.equals(this.repository, actionWorkflowRun.repository) &&
        Objects.equals(this.repositoryId, actionWorkflowRun.repositoryId) &&
        Objects.equals(this.runAttempt, actionWorkflowRun.runAttempt) &&
        Objects.equals(this.runNumber, actionWorkflowRun.runNumber) &&
        Objects.equals(this.startedAt, actionWorkflowRun.startedAt) &&
        Objects.equals(this.status, actionWorkflowRun.status) &&
        Objects.equals(this.triggerActor, actionWorkflowRun.triggerActor) &&
        Objects.equals(this.url, actionWorkflowRun.url);
  }

  @Override
  public int hashCode() {
    return Objects.hash(actor, completedAt, conclusion, displayTitle, event, headBranch, headRepository, headSha, htmlUrl, id, path, repository, repositoryId, runAttempt, runNumber, startedAt, status, triggerActor, url);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ActionWorkflowRun {\n");
    
    sb.append("    actor: ").append(toIndentedString(actor)).append("\n");
    sb.append("    completedAt: ").append(toIndentedString(completedAt)).append("\n");
    sb.append("    conclusion: ").append(toIndentedString(conclusion)).append("\n");
    sb.append("    displayTitle: ").append(toIndentedString(displayTitle)).append("\n");
    sb.append("    event: ").append(toIndentedString(event)).append("\n");
    sb.append("    headBranch: ").append(toIndentedString(headBranch)).append("\n");
    sb.append("    headRepository: ").append(toIndentedString(headRepository)).append("\n");
    sb.append("    headSha: ").append(toIndentedString(headSha)).append("\n");
    sb.append("    htmlUrl: ").append(toIndentedString(htmlUrl)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    path: ").append(toIndentedString(path)).append("\n");
    sb.append("    repository: ").append(toIndentedString(repository)).append("\n");
    sb.append("    repositoryId: ").append(toIndentedString(repositoryId)).append("\n");
    sb.append("    runAttempt: ").append(toIndentedString(runAttempt)).append("\n");
    sb.append("    runNumber: ").append(toIndentedString(runNumber)).append("\n");
    sb.append("    startedAt: ").append(toIndentedString(startedAt)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    triggerActor: ").append(toIndentedString(triggerActor)).append("\n");
    sb.append("    url: ").append(toIndentedString(url)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

