/*
 * Gitea API
 * This documentation describes the Gitea API.
 *
 * OpenAPI spec version: 1.24.7
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.gitea.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * ActionWorkflowRun represents a WorkflowRun
 */
@ApiModel(description = "ActionWorkflowRun represents a WorkflowRun")

public class ActionWorkflowRun {
  @SerializedName("head_sha")
  private String headSha = null;

  @SerializedName("id")
  private Long id = null;

  @SerializedName("repository_id")
  private Long repositoryId = null;

  public ActionWorkflowRun headSha(String headSha) {
    this.headSha = headSha;
    return this;
  }

   /**
   * Get headSha
   * @return headSha
  **/
  @ApiModelProperty(value = "")
  public String getHeadSha() {
    return headSha;
  }

  public void setHeadSha(String headSha) {
    this.headSha = headSha;
  }

  public ActionWorkflowRun id(Long id) {
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @ApiModelProperty(value = "")
  public Long getId() {
    return id;
  }

  public void setId(Long id) {
    this.id = id;
  }

  public ActionWorkflowRun repositoryId(Long repositoryId) {
    this.repositoryId = repositoryId;
    return this;
  }

   /**
   * Get repositoryId
   * @return repositoryId
  **/
  @ApiModelProperty(value = "")
  public Long getRepositoryId() {
    return repositoryId;
  }

  public void setRepositoryId(Long repositoryId) {
    this.repositoryId = repositoryId;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ActionWorkflowRun actionWorkflowRun = (ActionWorkflowRun) o;
    return Objects.equals(this.headSha, actionWorkflowRun.headSha) &&
        Objects.equals(this.id, actionWorkflowRun.id) &&
        Objects.equals(this.repositoryId, actionWorkflowRun.repositoryId);
  }

  @Override
  public int hashCode() {
    return Objects.hash(headSha, id, repositoryId);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ActionWorkflowRun {\n");
    
    sb.append("    headSha: ").append(toIndentedString(headSha)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    repositoryId: ").append(toIndentedString(repositoryId)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

