/*
 * Gitea API
 * This documentation describes the Gitea API.
 *
 * OpenAPI spec version: 1.25.3
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.gitea.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.gitea.model.ActionWorkflowStep;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.threeten.bp.OffsetDateTime;

/**
 * ActionWorkflowJob represents a WorkflowJob
 */
@ApiModel(description = "ActionWorkflowJob represents a WorkflowJob")

public class ActionWorkflowJob {
  @SerializedName("completed_at")
  private OffsetDateTime completedAt = null;

  @SerializedName("conclusion")
  private String conclusion = null;

  @SerializedName("created_at")
  private OffsetDateTime createdAt = null;

  @SerializedName("head_branch")
  private String headBranch = null;

  @SerializedName("head_sha")
  private String headSha = null;

  @SerializedName("html_url")
  private String htmlUrl = null;

  @SerializedName("id")
  private Long id = null;

  @SerializedName("labels")
  private List<String> labels = null;

  @SerializedName("name")
  private String name = null;

  @SerializedName("run_attempt")
  private Long runAttempt = null;

  @SerializedName("run_id")
  private Long runId = null;

  @SerializedName("run_url")
  private String runUrl = null;

  @SerializedName("runner_id")
  private Long runnerId = null;

  @SerializedName("runner_name")
  private String runnerName = null;

  @SerializedName("started_at")
  private OffsetDateTime startedAt = null;

  @SerializedName("status")
  private String status = null;

  @SerializedName("steps")
  private List<ActionWorkflowStep> steps = null;

  @SerializedName("url")
  private String url = null;

  public ActionWorkflowJob completedAt(OffsetDateTime completedAt) {
    this.completedAt = completedAt;
    return this;
  }

   /**
   * Get completedAt
   * @return completedAt
  **/
  @ApiModelProperty(value = "")
  public OffsetDateTime getCompletedAt() {
    return completedAt;
  }

  public void setCompletedAt(OffsetDateTime completedAt) {
    this.completedAt = completedAt;
  }

  public ActionWorkflowJob conclusion(String conclusion) {
    this.conclusion = conclusion;
    return this;
  }

   /**
   * Get conclusion
   * @return conclusion
  **/
  @ApiModelProperty(value = "")
  public String getConclusion() {
    return conclusion;
  }

  public void setConclusion(String conclusion) {
    this.conclusion = conclusion;
  }

  public ActionWorkflowJob createdAt(OffsetDateTime createdAt) {
    this.createdAt = createdAt;
    return this;
  }

   /**
   * Get createdAt
   * @return createdAt
  **/
  @ApiModelProperty(value = "")
  public OffsetDateTime getCreatedAt() {
    return createdAt;
  }

  public void setCreatedAt(OffsetDateTime createdAt) {
    this.createdAt = createdAt;
  }

  public ActionWorkflowJob headBranch(String headBranch) {
    this.headBranch = headBranch;
    return this;
  }

   /**
   * Get headBranch
   * @return headBranch
  **/
  @ApiModelProperty(value = "")
  public String getHeadBranch() {
    return headBranch;
  }

  public void setHeadBranch(String headBranch) {
    this.headBranch = headBranch;
  }

  public ActionWorkflowJob headSha(String headSha) {
    this.headSha = headSha;
    return this;
  }

   /**
   * Get headSha
   * @return headSha
  **/
  @ApiModelProperty(value = "")
  public String getHeadSha() {
    return headSha;
  }

  public void setHeadSha(String headSha) {
    this.headSha = headSha;
  }

  public ActionWorkflowJob htmlUrl(String htmlUrl) {
    this.htmlUrl = htmlUrl;
    return this;
  }

   /**
   * Get htmlUrl
   * @return htmlUrl
  **/
  @ApiModelProperty(value = "")
  public String getHtmlUrl() {
    return htmlUrl;
  }

  public void setHtmlUrl(String htmlUrl) {
    this.htmlUrl = htmlUrl;
  }

  public ActionWorkflowJob id(Long id) {
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @ApiModelProperty(value = "")
  public Long getId() {
    return id;
  }

  public void setId(Long id) {
    this.id = id;
  }

  public ActionWorkflowJob labels(List<String> labels) {
    this.labels = labels;
    return this;
  }

  public ActionWorkflowJob addLabelsItem(String labelsItem) {
    if (this.labels == null) {
      this.labels = new ArrayList<String>();
    }
    this.labels.add(labelsItem);
    return this;
  }

   /**
   * Get labels
   * @return labels
  **/
  @ApiModelProperty(value = "")
  public List<String> getLabels() {
    return labels;
  }

  public void setLabels(List<String> labels) {
    this.labels = labels;
  }

  public ActionWorkflowJob name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Get name
   * @return name
  **/
  @ApiModelProperty(value = "")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public ActionWorkflowJob runAttempt(Long runAttempt) {
    this.runAttempt = runAttempt;
    return this;
  }

   /**
   * Get runAttempt
   * @return runAttempt
  **/
  @ApiModelProperty(value = "")
  public Long getRunAttempt() {
    return runAttempt;
  }

  public void setRunAttempt(Long runAttempt) {
    this.runAttempt = runAttempt;
  }

  public ActionWorkflowJob runId(Long runId) {
    this.runId = runId;
    return this;
  }

   /**
   * Get runId
   * @return runId
  **/
  @ApiModelProperty(value = "")
  public Long getRunId() {
    return runId;
  }

  public void setRunId(Long runId) {
    this.runId = runId;
  }

  public ActionWorkflowJob runUrl(String runUrl) {
    this.runUrl = runUrl;
    return this;
  }

   /**
   * Get runUrl
   * @return runUrl
  **/
  @ApiModelProperty(value = "")
  public String getRunUrl() {
    return runUrl;
  }

  public void setRunUrl(String runUrl) {
    this.runUrl = runUrl;
  }

  public ActionWorkflowJob runnerId(Long runnerId) {
    this.runnerId = runnerId;
    return this;
  }

   /**
   * Get runnerId
   * @return runnerId
  **/
  @ApiModelProperty(value = "")
  public Long getRunnerId() {
    return runnerId;
  }

  public void setRunnerId(Long runnerId) {
    this.runnerId = runnerId;
  }

  public ActionWorkflowJob runnerName(String runnerName) {
    this.runnerName = runnerName;
    return this;
  }

   /**
   * Get runnerName
   * @return runnerName
  **/
  @ApiModelProperty(value = "")
  public String getRunnerName() {
    return runnerName;
  }

  public void setRunnerName(String runnerName) {
    this.runnerName = runnerName;
  }

  public ActionWorkflowJob startedAt(OffsetDateTime startedAt) {
    this.startedAt = startedAt;
    return this;
  }

   /**
   * Get startedAt
   * @return startedAt
  **/
  @ApiModelProperty(value = "")
  public OffsetDateTime getStartedAt() {
    return startedAt;
  }

  public void setStartedAt(OffsetDateTime startedAt) {
    this.startedAt = startedAt;
  }

  public ActionWorkflowJob status(String status) {
    this.status = status;
    return this;
  }

   /**
   * Get status
   * @return status
  **/
  @ApiModelProperty(value = "")
  public String getStatus() {
    return status;
  }

  public void setStatus(String status) {
    this.status = status;
  }

  public ActionWorkflowJob steps(List<ActionWorkflowStep> steps) {
    this.steps = steps;
    return this;
  }

  public ActionWorkflowJob addStepsItem(ActionWorkflowStep stepsItem) {
    if (this.steps == null) {
      this.steps = new ArrayList<ActionWorkflowStep>();
    }
    this.steps.add(stepsItem);
    return this;
  }

   /**
   * Get steps
   * @return steps
  **/
  @ApiModelProperty(value = "")
  public List<ActionWorkflowStep> getSteps() {
    return steps;
  }

  public void setSteps(List<ActionWorkflowStep> steps) {
    this.steps = steps;
  }

  public ActionWorkflowJob url(String url) {
    this.url = url;
    return this;
  }

   /**
   * Get url
   * @return url
  **/
  @ApiModelProperty(value = "")
  public String getUrl() {
    return url;
  }

  public void setUrl(String url) {
    this.url = url;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ActionWorkflowJob actionWorkflowJob = (ActionWorkflowJob) o;
    return Objects.equals(this.completedAt, actionWorkflowJob.completedAt) &&
        Objects.equals(this.conclusion, actionWorkflowJob.conclusion) &&
        Objects.equals(this.createdAt, actionWorkflowJob.createdAt) &&
        Objects.equals(this.headBranch, actionWorkflowJob.headBranch) &&
        Objects.equals(this.headSha, actionWorkflowJob.headSha) &&
        Objects.equals(this.htmlUrl, actionWorkflowJob.htmlUrl) &&
        Objects.equals(this.id, actionWorkflowJob.id) &&
        Objects.equals(this.labels, actionWorkflowJob.labels) &&
        Objects.equals(this.name, actionWorkflowJob.name) &&
        Objects.equals(this.runAttempt, actionWorkflowJob.runAttempt) &&
        Objects.equals(this.runId, actionWorkflowJob.runId) &&
        Objects.equals(this.runUrl, actionWorkflowJob.runUrl) &&
        Objects.equals(this.runnerId, actionWorkflowJob.runnerId) &&
        Objects.equals(this.runnerName, actionWorkflowJob.runnerName) &&
        Objects.equals(this.startedAt, actionWorkflowJob.startedAt) &&
        Objects.equals(this.status, actionWorkflowJob.status) &&
        Objects.equals(this.steps, actionWorkflowJob.steps) &&
        Objects.equals(this.url, actionWorkflowJob.url);
  }

  @Override
  public int hashCode() {
    return Objects.hash(completedAt, conclusion, createdAt, headBranch, headSha, htmlUrl, id, labels, name, runAttempt, runId, runUrl, runnerId, runnerName, startedAt, status, steps, url);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ActionWorkflowJob {\n");
    
    sb.append("    completedAt: ").append(toIndentedString(completedAt)).append("\n");
    sb.append("    conclusion: ").append(toIndentedString(conclusion)).append("\n");
    sb.append("    createdAt: ").append(toIndentedString(createdAt)).append("\n");
    sb.append("    headBranch: ").append(toIndentedString(headBranch)).append("\n");
    sb.append("    headSha: ").append(toIndentedString(headSha)).append("\n");
    sb.append("    htmlUrl: ").append(toIndentedString(htmlUrl)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    labels: ").append(toIndentedString(labels)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    runAttempt: ").append(toIndentedString(runAttempt)).append("\n");
    sb.append("    runId: ").append(toIndentedString(runId)).append("\n");
    sb.append("    runUrl: ").append(toIndentedString(runUrl)).append("\n");
    sb.append("    runnerId: ").append(toIndentedString(runnerId)).append("\n");
    sb.append("    runnerName: ").append(toIndentedString(runnerName)).append("\n");
    sb.append("    startedAt: ").append(toIndentedString(startedAt)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    steps: ").append(toIndentedString(steps)).append("\n");
    sb.append("    url: ").append(toIndentedString(url)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

