/*
 * Gitea API
 * This documentation describes the Gitea API.
 *
 * OpenAPI spec version: 1.25.3
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.gitea.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.gitea.model.ActionWorkflowJob;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * ActionWorkflowJobsResponse returns ActionWorkflowJobs
 */
@ApiModel(description = "ActionWorkflowJobsResponse returns ActionWorkflowJobs")

public class ActionWorkflowJobsResponse {
  @SerializedName("jobs")
  private List<ActionWorkflowJob> jobs = null;

  @SerializedName("total_count")
  private Long totalCount = null;

  public ActionWorkflowJobsResponse jobs(List<ActionWorkflowJob> jobs) {
    this.jobs = jobs;
    return this;
  }

  public ActionWorkflowJobsResponse addJobsItem(ActionWorkflowJob jobsItem) {
    if (this.jobs == null) {
      this.jobs = new ArrayList<ActionWorkflowJob>();
    }
    this.jobs.add(jobsItem);
    return this;
  }

   /**
   * Get jobs
   * @return jobs
  **/
  @ApiModelProperty(value = "")
  public List<ActionWorkflowJob> getJobs() {
    return jobs;
  }

  public void setJobs(List<ActionWorkflowJob> jobs) {
    this.jobs = jobs;
  }

  public ActionWorkflowJobsResponse totalCount(Long totalCount) {
    this.totalCount = totalCount;
    return this;
  }

   /**
   * Get totalCount
   * @return totalCount
  **/
  @ApiModelProperty(value = "")
  public Long getTotalCount() {
    return totalCount;
  }

  public void setTotalCount(Long totalCount) {
    this.totalCount = totalCount;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ActionWorkflowJobsResponse actionWorkflowJobsResponse = (ActionWorkflowJobsResponse) o;
    return Objects.equals(this.jobs, actionWorkflowJobsResponse.jobs) &&
        Objects.equals(this.totalCount, actionWorkflowJobsResponse.totalCount);
  }

  @Override
  public int hashCode() {
    return Objects.hash(jobs, totalCount);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ActionWorkflowJobsResponse {\n");
    
    sb.append("    jobs: ").append(toIndentedString(jobs)).append("\n");
    sb.append("    totalCount: ").append(toIndentedString(totalCount)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

