/*
 * Gitea API
 * This documentation describes the Gitea API.
 *
 * OpenAPI spec version: 1.24.7
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.gitea.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.gitea.model.ActionTask;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * ActionTaskResponse returns a ActionTask
 */
@ApiModel(description = "ActionTaskResponse returns a ActionTask")

public class ActionTaskResponse {
  @SerializedName("total_count")
  private Long totalCount = null;

  @SerializedName("workflow_runs")
  private List<ActionTask> workflowRuns = null;

  public ActionTaskResponse totalCount(Long totalCount) {
    this.totalCount = totalCount;
    return this;
  }

   /**
   * Get totalCount
   * @return totalCount
  **/
  @ApiModelProperty(value = "")
  public Long getTotalCount() {
    return totalCount;
  }

  public void setTotalCount(Long totalCount) {
    this.totalCount = totalCount;
  }

  public ActionTaskResponse workflowRuns(List<ActionTask> workflowRuns) {
    this.workflowRuns = workflowRuns;
    return this;
  }

  public ActionTaskResponse addWorkflowRunsItem(ActionTask workflowRunsItem) {
    if (this.workflowRuns == null) {
      this.workflowRuns = new ArrayList<ActionTask>();
    }
    this.workflowRuns.add(workflowRunsItem);
    return this;
  }

   /**
   * Get workflowRuns
   * @return workflowRuns
  **/
  @ApiModelProperty(value = "")
  public List<ActionTask> getWorkflowRuns() {
    return workflowRuns;
  }

  public void setWorkflowRuns(List<ActionTask> workflowRuns) {
    this.workflowRuns = workflowRuns;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ActionTaskResponse actionTaskResponse = (ActionTaskResponse) o;
    return Objects.equals(this.totalCount, actionTaskResponse.totalCount) &&
        Objects.equals(this.workflowRuns, actionTaskResponse.workflowRuns);
  }

  @Override
  public int hashCode() {
    return Objects.hash(totalCount, workflowRuns);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ActionTaskResponse {\n");
    
    sb.append("    totalCount: ").append(toIndentedString(totalCount)).append("\n");
    sb.append("    workflowRuns: ").append(toIndentedString(workflowRuns)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

