/*
 * Gitea API
 * This documentation describes the Gitea API.
 *
 * OpenAPI spec version: 1.24.6
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.gitea.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.gitea.model.Comment;
import io.gitea.model.Repository;
import io.gitea.model.User;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.threeten.bp.OffsetDateTime;

/**
 * Activity
 */

public class Activity {
  @SerializedName("act_user")
  private User actUser = null;

  @SerializedName("act_user_id")
  private Long actUserId = null;

  @SerializedName("comment")
  private Comment comment = null;

  @SerializedName("comment_id")
  private Long commentId = null;

  @SerializedName("content")
  private String content = null;

  @SerializedName("created")
  private OffsetDateTime created = null;

  @SerializedName("id")
  private Long id = null;

  @SerializedName("is_private")
  private Boolean isPrivate = null;

  /**
   * the type of action
   */
  @JsonAdapter(OpTypeEnum.Adapter.class)
  public enum OpTypeEnum {
    CREATE_REPO("create_repo"),
    
    RENAME_REPO("rename_repo"),
    
    STAR_REPO("star_repo"),
    
    WATCH_REPO("watch_repo"),
    
    COMMIT_REPO("commit_repo"),
    
    CREATE_ISSUE("create_issue"),
    
    CREATE_PULL_REQUEST("create_pull_request"),
    
    TRANSFER_REPO("transfer_repo"),
    
    PUSH_TAG("push_tag"),
    
    COMMENT_ISSUE("comment_issue"),
    
    MERGE_PULL_REQUEST("merge_pull_request"),
    
    CLOSE_ISSUE("close_issue"),
    
    REOPEN_ISSUE("reopen_issue"),
    
    CLOSE_PULL_REQUEST("close_pull_request"),
    
    REOPEN_PULL_REQUEST("reopen_pull_request"),
    
    DELETE_TAG("delete_tag"),
    
    DELETE_BRANCH("delete_branch"),
    
    MIRROR_SYNC_PUSH("mirror_sync_push"),
    
    MIRROR_SYNC_CREATE("mirror_sync_create"),
    
    MIRROR_SYNC_DELETE("mirror_sync_delete"),
    
    APPROVE_PULL_REQUEST("approve_pull_request"),
    
    REJECT_PULL_REQUEST("reject_pull_request"),
    
    COMMENT_PULL("comment_pull"),
    
    PUBLISH_RELEASE("publish_release"),
    
    PULL_REVIEW_DISMISSED("pull_review_dismissed"),
    
    PULL_REQUEST_READY_FOR_REVIEW("pull_request_ready_for_review"),
    
    AUTO_MERGE_PULL_REQUEST("auto_merge_pull_request");

    private String value;

    OpTypeEnum(String value) {
      this.value = value;
    }

    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    public static OpTypeEnum fromValue(String text) {
      for (OpTypeEnum b : OpTypeEnum.values()) {
        if (String.valueOf(b.value).equals(text)) {
          return b;
        }
      }
      return null;
    }

    public static class Adapter extends TypeAdapter<OpTypeEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final OpTypeEnum enumeration) throws IOException {
        jsonWriter.value(enumeration.getValue());
      }

      @Override
      public OpTypeEnum read(final JsonReader jsonReader) throws IOException {
        String value = jsonReader.nextString();
        return OpTypeEnum.fromValue(String.valueOf(value));
      }
    }
  }

  @SerializedName("op_type")
  private OpTypeEnum opType = null;

  @SerializedName("ref_name")
  private String refName = null;

  @SerializedName("repo")
  private Repository repo = null;

  @SerializedName("repo_id")
  private Long repoId = null;

  @SerializedName("user_id")
  private Long userId = null;

  public Activity actUser(User actUser) {
    this.actUser = actUser;
    return this;
  }

   /**
   * Get actUser
   * @return actUser
  **/
  @ApiModelProperty(value = "")
  public User getActUser() {
    return actUser;
  }

  public void setActUser(User actUser) {
    this.actUser = actUser;
  }

  public Activity actUserId(Long actUserId) {
    this.actUserId = actUserId;
    return this;
  }

   /**
   * Get actUserId
   * @return actUserId
  **/
  @ApiModelProperty(value = "")
  public Long getActUserId() {
    return actUserId;
  }

  public void setActUserId(Long actUserId) {
    this.actUserId = actUserId;
  }

  public Activity comment(Comment comment) {
    this.comment = comment;
    return this;
  }

   /**
   * Get comment
   * @return comment
  **/
  @ApiModelProperty(value = "")
  public Comment getComment() {
    return comment;
  }

  public void setComment(Comment comment) {
    this.comment = comment;
  }

  public Activity commentId(Long commentId) {
    this.commentId = commentId;
    return this;
  }

   /**
   * Get commentId
   * @return commentId
  **/
  @ApiModelProperty(value = "")
  public Long getCommentId() {
    return commentId;
  }

  public void setCommentId(Long commentId) {
    this.commentId = commentId;
  }

  public Activity content(String content) {
    this.content = content;
    return this;
  }

   /**
   * Get content
   * @return content
  **/
  @ApiModelProperty(value = "")
  public String getContent() {
    return content;
  }

  public void setContent(String content) {
    this.content = content;
  }

  public Activity created(OffsetDateTime created) {
    this.created = created;
    return this;
  }

   /**
   * Get created
   * @return created
  **/
  @ApiModelProperty(value = "")
  public OffsetDateTime getCreated() {
    return created;
  }

  public void setCreated(OffsetDateTime created) {
    this.created = created;
  }

  public Activity id(Long id) {
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @ApiModelProperty(value = "")
  public Long getId() {
    return id;
  }

  public void setId(Long id) {
    this.id = id;
  }

  public Activity isPrivate(Boolean isPrivate) {
    this.isPrivate = isPrivate;
    return this;
  }

   /**
   * Get isPrivate
   * @return isPrivate
  **/
  @ApiModelProperty(value = "")
  public Boolean isIsPrivate() {
    return isPrivate;
  }

  public void setIsPrivate(Boolean isPrivate) {
    this.isPrivate = isPrivate;
  }

  public Activity opType(OpTypeEnum opType) {
    this.opType = opType;
    return this;
  }

   /**
   * the type of action
   * @return opType
  **/
  @ApiModelProperty(value = "the type of action")
  public OpTypeEnum getOpType() {
    return opType;
  }

  public void setOpType(OpTypeEnum opType) {
    this.opType = opType;
  }

  public Activity refName(String refName) {
    this.refName = refName;
    return this;
  }

   /**
   * Get refName
   * @return refName
  **/
  @ApiModelProperty(value = "")
  public String getRefName() {
    return refName;
  }

  public void setRefName(String refName) {
    this.refName = refName;
  }

  public Activity repo(Repository repo) {
    this.repo = repo;
    return this;
  }

   /**
   * Get repo
   * @return repo
  **/
  @ApiModelProperty(value = "")
  public Repository getRepo() {
    return repo;
  }

  public void setRepo(Repository repo) {
    this.repo = repo;
  }

  public Activity repoId(Long repoId) {
    this.repoId = repoId;
    return this;
  }

   /**
   * Get repoId
   * @return repoId
  **/
  @ApiModelProperty(value = "")
  public Long getRepoId() {
    return repoId;
  }

  public void setRepoId(Long repoId) {
    this.repoId = repoId;
  }

  public Activity userId(Long userId) {
    this.userId = userId;
    return this;
  }

   /**
   * Get userId
   * @return userId
  **/
  @ApiModelProperty(value = "")
  public Long getUserId() {
    return userId;
  }

  public void setUserId(Long userId) {
    this.userId = userId;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Activity activity = (Activity) o;
    return Objects.equals(this.actUser, activity.actUser) &&
        Objects.equals(this.actUserId, activity.actUserId) &&
        Objects.equals(this.comment, activity.comment) &&
        Objects.equals(this.commentId, activity.commentId) &&
        Objects.equals(this.content, activity.content) &&
        Objects.equals(this.created, activity.created) &&
        Objects.equals(this.id, activity.id) &&
        Objects.equals(this.isPrivate, activity.isPrivate) &&
        Objects.equals(this.opType, activity.opType) &&
        Objects.equals(this.refName, activity.refName) &&
        Objects.equals(this.repo, activity.repo) &&
        Objects.equals(this.repoId, activity.repoId) &&
        Objects.equals(this.userId, activity.userId);
  }

  @Override
  public int hashCode() {
    return Objects.hash(actUser, actUserId, comment, commentId, content, created, id, isPrivate, opType, refName, repo, repoId, userId);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Activity {\n");
    
    sb.append("    actUser: ").append(toIndentedString(actUser)).append("\n");
    sb.append("    actUserId: ").append(toIndentedString(actUserId)).append("\n");
    sb.append("    comment: ").append(toIndentedString(comment)).append("\n");
    sb.append("    commentId: ").append(toIndentedString(commentId)).append("\n");
    sb.append("    content: ").append(toIndentedString(content)).append("\n");
    sb.append("    created: ").append(toIndentedString(created)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    isPrivate: ").append(toIndentedString(isPrivate)).append("\n");
    sb.append("    opType: ").append(toIndentedString(opType)).append("\n");
    sb.append("    refName: ").append(toIndentedString(refName)).append("\n");
    sb.append("    repo: ").append(toIndentedString(repo)).append("\n");
    sb.append("    repoId: ").append(toIndentedString(repoId)).append("\n");
    sb.append("    userId: ").append(toIndentedString(userId)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

