/*
 * Gitea API
 * This documentation describes the Gitea API.
 *
 * OpenAPI spec version: 1.25.4
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.gitea.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.gitea.model.ActionRunner;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * ActionRunnersResponse returns Runners
 */
@ApiModel(description = "ActionRunnersResponse returns Runners")

public class ActionRunnersResponse {
  @SerializedName("runners")
  private List<ActionRunner> runners = null;

  @SerializedName("total_count")
  private Long totalCount = null;

  public ActionRunnersResponse runners(List<ActionRunner> runners) {
    this.runners = runners;
    return this;
  }

  public ActionRunnersResponse addRunnersItem(ActionRunner runnersItem) {
    if (this.runners == null) {
      this.runners = new ArrayList<ActionRunner>();
    }
    this.runners.add(runnersItem);
    return this;
  }

   /**
   * Get runners
   * @return runners
  **/
  @ApiModelProperty(value = "")
  public List<ActionRunner> getRunners() {
    return runners;
  }

  public void setRunners(List<ActionRunner> runners) {
    this.runners = runners;
  }

  public ActionRunnersResponse totalCount(Long totalCount) {
    this.totalCount = totalCount;
    return this;
  }

   /**
   * Get totalCount
   * @return totalCount
  **/
  @ApiModelProperty(value = "")
  public Long getTotalCount() {
    return totalCount;
  }

  public void setTotalCount(Long totalCount) {
    this.totalCount = totalCount;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ActionRunnersResponse actionRunnersResponse = (ActionRunnersResponse) o;
    return Objects.equals(this.runners, actionRunnersResponse.runners) &&
        Objects.equals(this.totalCount, actionRunnersResponse.totalCount);
  }

  @Override
  public int hashCode() {
    return Objects.hash(runners, totalCount);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ActionRunnersResponse {\n");
    
    sb.append("    runners: ").append(toIndentedString(runners)).append("\n");
    sb.append("    totalCount: ").append(toIndentedString(totalCount)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

