/*
 * Gitea API
 * This documentation describes the Gitea API.
 *
 * OpenAPI spec version: 1.26.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.gitea.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * CommitAffectedFiles store information about files affected by the commit
 */
@ApiModel(description = "CommitAffectedFiles store information about files affected by the commit")

public class CommitAffectedFiles {
  @SerializedName("filename")
  private String filename = null;

  @SerializedName("status")
  private String status = null;

  public CommitAffectedFiles filename(String filename) {
    this.filename = filename;
    return this;
  }

   /**
   * Filename is the path of the affected file
   * @return filename
  **/
  @ApiModelProperty(value = "Filename is the path of the affected file")
  public String getFilename() {
    return filename;
  }

  public void setFilename(String filename) {
    this.filename = filename;
  }

  public CommitAffectedFiles status(String status) {
    this.status = status;
    return this;
  }

   /**
   * Status indicates how the file was affected (added, modified, deleted)
   * @return status
  **/
  @ApiModelProperty(value = "Status indicates how the file was affected (added, modified, deleted)")
  public String getStatus() {
    return status;
  }

  public void setStatus(String status) {
    this.status = status;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CommitAffectedFiles commitAffectedFiles = (CommitAffectedFiles) o;
    return Objects.equals(this.filename, commitAffectedFiles.filename) &&
        Objects.equals(this.status, commitAffectedFiles.status);
  }

  @Override
  public int hashCode() {
    return Objects.hash(filename, status);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CommitAffectedFiles {\n");
    
    sb.append("    filename: ").append(toIndentedString(filename)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

