/*
 * Gitea API
 * This documentation describes the Gitea API.
 *
 * OpenAPI spec version: 1.24.2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.gitea.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.gitea.model.Commit;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * Compare
 */

public class Compare {
  @SerializedName("commits")
  private List<Commit> commits = null;

  @SerializedName("total_commits")
  private Long totalCommits = null;

  public Compare commits(List<Commit> commits) {
    this.commits = commits;
    return this;
  }

  public Compare addCommitsItem(Commit commitsItem) {
    if (this.commits == null) {
      this.commits = new ArrayList<Commit>();
    }
    this.commits.add(commitsItem);
    return this;
  }

   /**
   * Get commits
   * @return commits
  **/
  @ApiModelProperty(value = "")
  public List<Commit> getCommits() {
    return commits;
  }

  public void setCommits(List<Commit> commits) {
    this.commits = commits;
  }

  public Compare totalCommits(Long totalCommits) {
    this.totalCommits = totalCommits;
    return this;
  }

   /**
   * Get totalCommits
   * @return totalCommits
  **/
  @ApiModelProperty(value = "")
  public Long getTotalCommits() {
    return totalCommits;
  }

  public void setTotalCommits(Long totalCommits) {
    this.totalCommits = totalCommits;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Compare compare = (Compare) o;
    return Objects.equals(this.commits, compare.commits) &&
        Objects.equals(this.totalCommits, compare.totalCommits);
  }

  @Override
  public int hashCode() {
    return Objects.hash(commits, totalCommits);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Compare {\n");
    
    sb.append("    commits: ").append(toIndentedString(commits)).append("\n");
    sb.append("    totalCommits: ").append(toIndentedString(totalCommits)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

