/*
 * Gitea API
 * This documentation describes the Gitea API.
 *
 * OpenAPI spec version: 1.24.5
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.gitea.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * CreateVariableOption the option when creating variable
 */
@ApiModel(description = "CreateVariableOption the option when creating variable")

public class CreateVariableOption {
  @SerializedName("description")
  private String description = null;

  @SerializedName("value")
  private String value = null;

  public CreateVariableOption description(String description) {
    this.description = description;
    return this;
  }

   /**
   * Description of the variable to create
   * @return description
  **/
  @ApiModelProperty(value = "Description of the variable to create")
  public String getDescription() {
    return description;
  }

  public void setDescription(String description) {
    this.description = description;
  }

  public CreateVariableOption value(String value) {
    this.value = value;
    return this;
  }

   /**
   * Value of the variable to create
   * @return value
  **/
  @ApiModelProperty(required = true, value = "Value of the variable to create")
  public String getValue() {
    return value;
  }

  public void setValue(String value) {
    this.value = value;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CreateVariableOption createVariableOption = (CreateVariableOption) o;
    return Objects.equals(this.description, createVariableOption.description) &&
        Objects.equals(this.value, createVariableOption.value);
  }

  @Override
  public int hashCode() {
    return Objects.hash(description, value);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CreateVariableOption {\n");
    
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    value: ").append(toIndentedString(value)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

