/*
 * Gitea API
 * This documentation describes the Gitea API.
 *
 * OpenAPI spec version: 28.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.gitea.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * CreateProjectColumnOption represents options for creating a project column
 */
@ApiModel(description = "CreateProjectColumnOption represents options for creating a project column")

public class CreateProjectColumnOption {
  @SerializedName("color")
  private String color = null;

  @SerializedName("title")
  private String title = null;

  public CreateProjectColumnOption color(String color) {
    this.color = color;
    return this;
  }

   /**
   * Column color in 6-digit hex format, e.g. #FF0000
   * @return color
  **/
  @ApiModelProperty(value = "Column color in 6-digit hex format, e.g. #FF0000")
  public String getColor() {
    return color;
  }

  public void setColor(String color) {
    this.color = color;
  }

  public CreateProjectColumnOption title(String title) {
    this.title = title;
    return this;
  }

   /**
   * Get title
   * @return title
  **/
  @ApiModelProperty(required = true, value = "")
  public String getTitle() {
    return title;
  }

  public void setTitle(String title) {
    this.title = title;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CreateProjectColumnOption createProjectColumnOption = (CreateProjectColumnOption) o;
    return Objects.equals(this.color, createProjectColumnOption.color) &&
        Objects.equals(this.title, createProjectColumnOption.title);
  }

  @Override
  public int hashCode() {
    return Objects.hash(color, title);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CreateProjectColumnOption {\n");
    
    sb.append("    color: ").append(toIndentedString(color)).append("\n");
    sb.append("    title: ").append(toIndentedString(title)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

