/*
 * Gitea API
 * This documentation describes the Gitea API.
 *
 * OpenAPI spec version: 1.26.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.gitea.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.threeten.bp.OffsetDateTime;

/**
 * CreatePullRequestOption options when creating a pull request
 */
@ApiModel(description = "CreatePullRequestOption options when creating a pull request")

public class CreatePullRequestOption {
  @SerializedName("allow_maintainer_edit")
  private Boolean allowMaintainerEdit = null;

  @SerializedName("assignee")
  private String assignee = null;

  @SerializedName("assignees")
  private List<String> assignees = null;

  @SerializedName("base")
  private String base = null;

  @SerializedName("body")
  private String body = null;

  @SerializedName("due_date")
  private OffsetDateTime dueDate = null;

  @SerializedName("head")
  private String head = null;

  @SerializedName("labels")
  private List<Long> labels = null;

  @SerializedName("milestone")
  private Long milestone = null;

  @SerializedName("reviewers")
  private List<String> reviewers = null;

  @SerializedName("team_reviewers")
  private List<String> teamReviewers = null;

  @SerializedName("title")
  private String title = null;

  public CreatePullRequestOption allowMaintainerEdit(Boolean allowMaintainerEdit) {
    this.allowMaintainerEdit = allowMaintainerEdit;
    return this;
  }

   /**
   * Whether maintainers can edit the pull request
   * @return allowMaintainerEdit
  **/
  @ApiModelProperty(value = "Whether maintainers can edit the pull request")
  public Boolean isAllowMaintainerEdit() {
    return allowMaintainerEdit;
  }

  public void setAllowMaintainerEdit(Boolean allowMaintainerEdit) {
    this.allowMaintainerEdit = allowMaintainerEdit;
  }

  public CreatePullRequestOption assignee(String assignee) {
    this.assignee = assignee;
    return this;
  }

   /**
   * The primary assignee username
   * @return assignee
  **/
  @ApiModelProperty(value = "The primary assignee username")
  public String getAssignee() {
    return assignee;
  }

  public void setAssignee(String assignee) {
    this.assignee = assignee;
  }

  public CreatePullRequestOption assignees(List<String> assignees) {
    this.assignees = assignees;
    return this;
  }

  public CreatePullRequestOption addAssigneesItem(String assigneesItem) {
    if (this.assignees == null) {
      this.assignees = new ArrayList<String>();
    }
    this.assignees.add(assigneesItem);
    return this;
  }

   /**
   * The list of assignee usernames
   * @return assignees
  **/
  @ApiModelProperty(value = "The list of assignee usernames")
  public List<String> getAssignees() {
    return assignees;
  }

  public void setAssignees(List<String> assignees) {
    this.assignees = assignees;
  }

  public CreatePullRequestOption base(String base) {
    this.base = base;
    return this;
  }

   /**
   * The base branch for the pull request
   * @return base
  **/
  @ApiModelProperty(value = "The base branch for the pull request")
  public String getBase() {
    return base;
  }

  public void setBase(String base) {
    this.base = base;
  }

  public CreatePullRequestOption body(String body) {
    this.body = body;
    return this;
  }

   /**
   * The description body of the pull request
   * @return body
  **/
  @ApiModelProperty(value = "The description body of the pull request")
  public String getBody() {
    return body;
  }

  public void setBody(String body) {
    this.body = body;
  }

  public CreatePullRequestOption dueDate(OffsetDateTime dueDate) {
    this.dueDate = dueDate;
    return this;
  }

   /**
   * Get dueDate
   * @return dueDate
  **/
  @ApiModelProperty(value = "")
  public OffsetDateTime getDueDate() {
    return dueDate;
  }

  public void setDueDate(OffsetDateTime dueDate) {
    this.dueDate = dueDate;
  }

  public CreatePullRequestOption head(String head) {
    this.head = head;
    return this;
  }

   /**
   * The head branch for the pull request, it could be a branch name on the base repository or a form like &#x60;&lt;username&gt;:&lt;branch&gt;&#x60; which refers to the user&#39;s fork repository&#39;s branch.
   * @return head
  **/
  @ApiModelProperty(value = "The head branch for the pull request, it could be a branch name on the base repository or a form like `<username>:<branch>` which refers to the user's fork repository's branch.")
  public String getHead() {
    return head;
  }

  public void setHead(String head) {
    this.head = head;
  }

  public CreatePullRequestOption labels(List<Long> labels) {
    this.labels = labels;
    return this;
  }

  public CreatePullRequestOption addLabelsItem(Long labelsItem) {
    if (this.labels == null) {
      this.labels = new ArrayList<Long>();
    }
    this.labels.add(labelsItem);
    return this;
  }

   /**
   * The list of label IDs to assign to the pull request
   * @return labels
  **/
  @ApiModelProperty(value = "The list of label IDs to assign to the pull request")
  public List<Long> getLabels() {
    return labels;
  }

  public void setLabels(List<Long> labels) {
    this.labels = labels;
  }

  public CreatePullRequestOption milestone(Long milestone) {
    this.milestone = milestone;
    return this;
  }

   /**
   * The milestone ID to assign to the pull request
   * @return milestone
  **/
  @ApiModelProperty(value = "The milestone ID to assign to the pull request")
  public Long getMilestone() {
    return milestone;
  }

  public void setMilestone(Long milestone) {
    this.milestone = milestone;
  }

  public CreatePullRequestOption reviewers(List<String> reviewers) {
    this.reviewers = reviewers;
    return this;
  }

  public CreatePullRequestOption addReviewersItem(String reviewersItem) {
    if (this.reviewers == null) {
      this.reviewers = new ArrayList<String>();
    }
    this.reviewers.add(reviewersItem);
    return this;
  }

   /**
   * The list of reviewer usernames
   * @return reviewers
  **/
  @ApiModelProperty(value = "The list of reviewer usernames")
  public List<String> getReviewers() {
    return reviewers;
  }

  public void setReviewers(List<String> reviewers) {
    this.reviewers = reviewers;
  }

  public CreatePullRequestOption teamReviewers(List<String> teamReviewers) {
    this.teamReviewers = teamReviewers;
    return this;
  }

  public CreatePullRequestOption addTeamReviewersItem(String teamReviewersItem) {
    if (this.teamReviewers == null) {
      this.teamReviewers = new ArrayList<String>();
    }
    this.teamReviewers.add(teamReviewersItem);
    return this;
  }

   /**
   * The list of team reviewer names
   * @return teamReviewers
  **/
  @ApiModelProperty(value = "The list of team reviewer names")
  public List<String> getTeamReviewers() {
    return teamReviewers;
  }

  public void setTeamReviewers(List<String> teamReviewers) {
    this.teamReviewers = teamReviewers;
  }

  public CreatePullRequestOption title(String title) {
    this.title = title;
    return this;
  }

   /**
   * The title of the pull request
   * @return title
  **/
  @ApiModelProperty(value = "The title of the pull request")
  public String getTitle() {
    return title;
  }

  public void setTitle(String title) {
    this.title = title;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CreatePullRequestOption createPullRequestOption = (CreatePullRequestOption) o;
    return Objects.equals(this.allowMaintainerEdit, createPullRequestOption.allowMaintainerEdit) &&
        Objects.equals(this.assignee, createPullRequestOption.assignee) &&
        Objects.equals(this.assignees, createPullRequestOption.assignees) &&
        Objects.equals(this.base, createPullRequestOption.base) &&
        Objects.equals(this.body, createPullRequestOption.body) &&
        Objects.equals(this.dueDate, createPullRequestOption.dueDate) &&
        Objects.equals(this.head, createPullRequestOption.head) &&
        Objects.equals(this.labels, createPullRequestOption.labels) &&
        Objects.equals(this.milestone, createPullRequestOption.milestone) &&
        Objects.equals(this.reviewers, createPullRequestOption.reviewers) &&
        Objects.equals(this.teamReviewers, createPullRequestOption.teamReviewers) &&
        Objects.equals(this.title, createPullRequestOption.title);
  }

  @Override
  public int hashCode() {
    return Objects.hash(allowMaintainerEdit, assignee, assignees, base, body, dueDate, head, labels, milestone, reviewers, teamReviewers, title);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CreatePullRequestOption {\n");
    
    sb.append("    allowMaintainerEdit: ").append(toIndentedString(allowMaintainerEdit)).append("\n");
    sb.append("    assignee: ").append(toIndentedString(assignee)).append("\n");
    sb.append("    assignees: ").append(toIndentedString(assignees)).append("\n");
    sb.append("    base: ").append(toIndentedString(base)).append("\n");
    sb.append("    body: ").append(toIndentedString(body)).append("\n");
    sb.append("    dueDate: ").append(toIndentedString(dueDate)).append("\n");
    sb.append("    head: ").append(toIndentedString(head)).append("\n");
    sb.append("    labels: ").append(toIndentedString(labels)).append("\n");
    sb.append("    milestone: ").append(toIndentedString(milestone)).append("\n");
    sb.append("    reviewers: ").append(toIndentedString(reviewers)).append("\n");
    sb.append("    teamReviewers: ").append(toIndentedString(teamReviewers)).append("\n");
    sb.append("    title: ").append(toIndentedString(title)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

