/*
 * Gitea API
 * This documentation describes the Gitea API.
 *
 * OpenAPI spec version: 28.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.gitea.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * CreateProjectOption represents options for creating a project
 */
@ApiModel(description = "CreateProjectOption represents options for creating a project")

public class CreateProjectOption {
  @SerializedName("card_type")
  private String cardType = null;

  @SerializedName("description")
  private String description = null;

  @SerializedName("template_type")
  private String templateType = null;

  @SerializedName("title")
  private String title = null;

  public CreateProjectOption cardType(String cardType) {
    this.cardType = cardType;
    return this;
  }

   /**
   * Card type: \&quot;text_only\&quot; or \&quot;images_and_text\&quot;
   * @return cardType
  **/
  @ApiModelProperty(value = "Card type: \"text_only\" or \"images_and_text\"")
  public String getCardType() {
    return cardType;
  }

  public void setCardType(String cardType) {
    this.cardType = cardType;
  }

  public CreateProjectOption description(String description) {
    this.description = description;
    return this;
  }

   /**
   * Get description
   * @return description
  **/
  @ApiModelProperty(value = "")
  public String getDescription() {
    return description;
  }

  public void setDescription(String description) {
    this.description = description;
  }

  public CreateProjectOption templateType(String templateType) {
    this.templateType = templateType;
    return this;
  }

   /**
   * Template type: \&quot;none\&quot;, \&quot;basic_kanban\&quot; or \&quot;bug_triage\&quot;
   * @return templateType
  **/
  @ApiModelProperty(value = "Template type: \"none\", \"basic_kanban\" or \"bug_triage\"")
  public String getTemplateType() {
    return templateType;
  }

  public void setTemplateType(String templateType) {
    this.templateType = templateType;
  }

  public CreateProjectOption title(String title) {
    this.title = title;
    return this;
  }

   /**
   * Get title
   * @return title
  **/
  @ApiModelProperty(required = true, value = "")
  public String getTitle() {
    return title;
  }

  public void setTitle(String title) {
    this.title = title;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CreateProjectOption createProjectOption = (CreateProjectOption) o;
    return Objects.equals(this.cardType, createProjectOption.cardType) &&
        Objects.equals(this.description, createProjectOption.description) &&
        Objects.equals(this.templateType, createProjectOption.templateType) &&
        Objects.equals(this.title, createProjectOption.title);
  }

  @Override
  public int hashCode() {
    return Objects.hash(cardType, description, templateType, title);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CreateProjectOption {\n");
    
    sb.append("    cardType: ").append(toIndentedString(cardType)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    templateType: ").append(toIndentedString(templateType)).append("\n");
    sb.append("    title: ").append(toIndentedString(title)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

