/*
 * Gitea API
 * This documentation describes the Gitea API.
 *
 * OpenAPI spec version: 28.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.gitea.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * EditProjectColumnOption represents options for editing a project column
 */
@ApiModel(description = "EditProjectColumnOption represents options for editing a project column")

public class EditProjectColumnOption {
  @SerializedName("color")
  private String color = null;

  @SerializedName("sorting")
  private Long sorting = null;

  @SerializedName("title")
  private String title = null;

  public EditProjectColumnOption color(String color) {
    this.color = color;
    return this;
  }

   /**
   * Column color in 6-digit hex format, e.g. #FF0000
   * @return color
  **/
  @ApiModelProperty(value = "Column color in 6-digit hex format, e.g. #FF0000")
  public String getColor() {
    return color;
  }

  public void setColor(String color) {
    this.color = color;
  }

  public EditProjectColumnOption sorting(Long sorting) {
    this.sorting = sorting;
    return this;
  }

   /**
   * Position of the column within the project, between -128 and 127
   * @return sorting
  **/
  @ApiModelProperty(value = "Position of the column within the project, between -128 and 127")
  public Long getSorting() {
    return sorting;
  }

  public void setSorting(Long sorting) {
    this.sorting = sorting;
  }

  public EditProjectColumnOption title(String title) {
    this.title = title;
    return this;
  }

   /**
   * Get title
   * @return title
  **/
  @ApiModelProperty(value = "")
  public String getTitle() {
    return title;
  }

  public void setTitle(String title) {
    this.title = title;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    EditProjectColumnOption editProjectColumnOption = (EditProjectColumnOption) o;
    return Objects.equals(this.color, editProjectColumnOption.color) &&
        Objects.equals(this.sorting, editProjectColumnOption.sorting) &&
        Objects.equals(this.title, editProjectColumnOption.title);
  }

  @Override
  public int hashCode() {
    return Objects.hash(color, sorting, title);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class EditProjectColumnOption {\n");
    
    sb.append("    color: ").append(toIndentedString(color)).append("\n");
    sb.append("    sorting: ").append(toIndentedString(sorting)).append("\n");
    sb.append("    title: ").append(toIndentedString(title)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

