/*
 * Gitea API
 * This documentation describes the Gitea API.
 *
 * OpenAPI spec version: 1.26.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.gitea.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * EditTagProtectionOption options for editing a tag protection
 */
@ApiModel(description = "EditTagProtectionOption options for editing a tag protection")

public class EditTagProtectionOption {
  @SerializedName("name_pattern")
  private String namePattern = null;

  @SerializedName("whitelist_teams")
  private List<String> whitelistTeams = null;

  @SerializedName("whitelist_usernames")
  private List<String> whitelistUsernames = null;

  public EditTagProtectionOption namePattern(String namePattern) {
    this.namePattern = namePattern;
    return this;
  }

   /**
   * The pattern to match tag names for protection
   * @return namePattern
  **/
  @ApiModelProperty(value = "The pattern to match tag names for protection")
  public String getNamePattern() {
    return namePattern;
  }

  public void setNamePattern(String namePattern) {
    this.namePattern = namePattern;
  }

  public EditTagProtectionOption whitelistTeams(List<String> whitelistTeams) {
    this.whitelistTeams = whitelistTeams;
    return this;
  }

  public EditTagProtectionOption addWhitelistTeamsItem(String whitelistTeamsItem) {
    if (this.whitelistTeams == null) {
      this.whitelistTeams = new ArrayList<String>();
    }
    this.whitelistTeams.add(whitelistTeamsItem);
    return this;
  }

   /**
   * List of team names allowed to create/delete protected tags
   * @return whitelistTeams
  **/
  @ApiModelProperty(value = "List of team names allowed to create/delete protected tags")
  public List<String> getWhitelistTeams() {
    return whitelistTeams;
  }

  public void setWhitelistTeams(List<String> whitelistTeams) {
    this.whitelistTeams = whitelistTeams;
  }

  public EditTagProtectionOption whitelistUsernames(List<String> whitelistUsernames) {
    this.whitelistUsernames = whitelistUsernames;
    return this;
  }

  public EditTagProtectionOption addWhitelistUsernamesItem(String whitelistUsernamesItem) {
    if (this.whitelistUsernames == null) {
      this.whitelistUsernames = new ArrayList<String>();
    }
    this.whitelistUsernames.add(whitelistUsernamesItem);
    return this;
  }

   /**
   * List of usernames allowed to create/delete protected tags
   * @return whitelistUsernames
  **/
  @ApiModelProperty(value = "List of usernames allowed to create/delete protected tags")
  public List<String> getWhitelistUsernames() {
    return whitelistUsernames;
  }

  public void setWhitelistUsernames(List<String> whitelistUsernames) {
    this.whitelistUsernames = whitelistUsernames;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    EditTagProtectionOption editTagProtectionOption = (EditTagProtectionOption) o;
    return Objects.equals(this.namePattern, editTagProtectionOption.namePattern) &&
        Objects.equals(this.whitelistTeams, editTagProtectionOption.whitelistTeams) &&
        Objects.equals(this.whitelistUsernames, editTagProtectionOption.whitelistUsernames);
  }

  @Override
  public int hashCode() {
    return Objects.hash(namePattern, whitelistTeams, whitelistUsernames);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class EditTagProtectionOption {\n");
    
    sb.append("    namePattern: ").append(toIndentedString(namePattern)).append("\n");
    sb.append("    whitelistTeams: ").append(toIndentedString(whitelistTeams)).append("\n");
    sb.append("    whitelistUsernames: ").append(toIndentedString(whitelistUsernames)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

