/*
 * Gitea API
 * This documentation describes the Gitea API.
 *
 * OpenAPI spec version: 1.25.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.gitea.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.threeten.bp.OffsetDateTime;

/**
 * EditPullRequestOption options when modify pull request
 */
@ApiModel(description = "EditPullRequestOption options when modify pull request")

public class EditPullRequestOption {
  @SerializedName("allow_maintainer_edit")
  private Boolean allowMaintainerEdit = null;

  @SerializedName("assignee")
  private String assignee = null;

  @SerializedName("assignees")
  private List<String> assignees = null;

  @SerializedName("base")
  private String base = null;

  @SerializedName("body")
  private String body = null;

  @SerializedName("due_date")
  private OffsetDateTime dueDate = null;

  @SerializedName("labels")
  private List<Long> labels = null;

  @SerializedName("milestone")
  private Long milestone = null;

  @SerializedName("state")
  private String state = null;

  @SerializedName("title")
  private String title = null;

  @SerializedName("unset_due_date")
  private Boolean unsetDueDate = null;

  public EditPullRequestOption allowMaintainerEdit(Boolean allowMaintainerEdit) {
    this.allowMaintainerEdit = allowMaintainerEdit;
    return this;
  }

   /**
   * Whether to allow maintainer edits
   * @return allowMaintainerEdit
  **/
  @ApiModelProperty(value = "Whether to allow maintainer edits")
  public Boolean isAllowMaintainerEdit() {
    return allowMaintainerEdit;
  }

  public void setAllowMaintainerEdit(Boolean allowMaintainerEdit) {
    this.allowMaintainerEdit = allowMaintainerEdit;
  }

  public EditPullRequestOption assignee(String assignee) {
    this.assignee = assignee;
    return this;
  }

   /**
   * The new primary assignee username
   * @return assignee
  **/
  @ApiModelProperty(value = "The new primary assignee username")
  public String getAssignee() {
    return assignee;
  }

  public void setAssignee(String assignee) {
    this.assignee = assignee;
  }

  public EditPullRequestOption assignees(List<String> assignees) {
    this.assignees = assignees;
    return this;
  }

  public EditPullRequestOption addAssigneesItem(String assigneesItem) {
    if (this.assignees == null) {
      this.assignees = new ArrayList<String>();
    }
    this.assignees.add(assigneesItem);
    return this;
  }

   /**
   * The new list of assignee usernames
   * @return assignees
  **/
  @ApiModelProperty(value = "The new list of assignee usernames")
  public List<String> getAssignees() {
    return assignees;
  }

  public void setAssignees(List<String> assignees) {
    this.assignees = assignees;
  }

  public EditPullRequestOption base(String base) {
    this.base = base;
    return this;
  }

   /**
   * The new base branch for the pull request
   * @return base
  **/
  @ApiModelProperty(value = "The new base branch for the pull request")
  public String getBase() {
    return base;
  }

  public void setBase(String base) {
    this.base = base;
  }

  public EditPullRequestOption body(String body) {
    this.body = body;
    return this;
  }

   /**
   * The new description body for the pull request
   * @return body
  **/
  @ApiModelProperty(value = "The new description body for the pull request")
  public String getBody() {
    return body;
  }

  public void setBody(String body) {
    this.body = body;
  }

  public EditPullRequestOption dueDate(OffsetDateTime dueDate) {
    this.dueDate = dueDate;
    return this;
  }

   /**
   * Get dueDate
   * @return dueDate
  **/
  @ApiModelProperty(value = "")
  public OffsetDateTime getDueDate() {
    return dueDate;
  }

  public void setDueDate(OffsetDateTime dueDate) {
    this.dueDate = dueDate;
  }

  public EditPullRequestOption labels(List<Long> labels) {
    this.labels = labels;
    return this;
  }

  public EditPullRequestOption addLabelsItem(Long labelsItem) {
    if (this.labels == null) {
      this.labels = new ArrayList<Long>();
    }
    this.labels.add(labelsItem);
    return this;
  }

   /**
   * The new list of label IDs for the pull request
   * @return labels
  **/
  @ApiModelProperty(value = "The new list of label IDs for the pull request")
  public List<Long> getLabels() {
    return labels;
  }

  public void setLabels(List<Long> labels) {
    this.labels = labels;
  }

  public EditPullRequestOption milestone(Long milestone) {
    this.milestone = milestone;
    return this;
  }

   /**
   * The new milestone ID for the pull request
   * @return milestone
  **/
  @ApiModelProperty(value = "The new milestone ID for the pull request")
  public Long getMilestone() {
    return milestone;
  }

  public void setMilestone(Long milestone) {
    this.milestone = milestone;
  }

  public EditPullRequestOption state(String state) {
    this.state = state;
    return this;
  }

   /**
   * The new state for the pull request
   * @return state
  **/
  @ApiModelProperty(value = "The new state for the pull request")
  public String getState() {
    return state;
  }

  public void setState(String state) {
    this.state = state;
  }

  public EditPullRequestOption title(String title) {
    this.title = title;
    return this;
  }

   /**
   * The new title for the pull request
   * @return title
  **/
  @ApiModelProperty(value = "The new title for the pull request")
  public String getTitle() {
    return title;
  }

  public void setTitle(String title) {
    this.title = title;
  }

  public EditPullRequestOption unsetDueDate(Boolean unsetDueDate) {
    this.unsetDueDate = unsetDueDate;
    return this;
  }

   /**
   * Whether to remove the current deadline
   * @return unsetDueDate
  **/
  @ApiModelProperty(value = "Whether to remove the current deadline")
  public Boolean isUnsetDueDate() {
    return unsetDueDate;
  }

  public void setUnsetDueDate(Boolean unsetDueDate) {
    this.unsetDueDate = unsetDueDate;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    EditPullRequestOption editPullRequestOption = (EditPullRequestOption) o;
    return Objects.equals(this.allowMaintainerEdit, editPullRequestOption.allowMaintainerEdit) &&
        Objects.equals(this.assignee, editPullRequestOption.assignee) &&
        Objects.equals(this.assignees, editPullRequestOption.assignees) &&
        Objects.equals(this.base, editPullRequestOption.base) &&
        Objects.equals(this.body, editPullRequestOption.body) &&
        Objects.equals(this.dueDate, editPullRequestOption.dueDate) &&
        Objects.equals(this.labels, editPullRequestOption.labels) &&
        Objects.equals(this.milestone, editPullRequestOption.milestone) &&
        Objects.equals(this.state, editPullRequestOption.state) &&
        Objects.equals(this.title, editPullRequestOption.title) &&
        Objects.equals(this.unsetDueDate, editPullRequestOption.unsetDueDate);
  }

  @Override
  public int hashCode() {
    return Objects.hash(allowMaintainerEdit, assignee, assignees, base, body, dueDate, labels, milestone, state, title, unsetDueDate);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class EditPullRequestOption {\n");
    
    sb.append("    allowMaintainerEdit: ").append(toIndentedString(allowMaintainerEdit)).append("\n");
    sb.append("    assignee: ").append(toIndentedString(assignee)).append("\n");
    sb.append("    assignees: ").append(toIndentedString(assignees)).append("\n");
    sb.append("    base: ").append(toIndentedString(base)).append("\n");
    sb.append("    body: ").append(toIndentedString(body)).append("\n");
    sb.append("    dueDate: ").append(toIndentedString(dueDate)).append("\n");
    sb.append("    labels: ").append(toIndentedString(labels)).append("\n");
    sb.append("    milestone: ").append(toIndentedString(milestone)).append("\n");
    sb.append("    state: ").append(toIndentedString(state)).append("\n");
    sb.append("    title: ").append(toIndentedString(title)).append("\n");
    sb.append("    unsetDueDate: ").append(toIndentedString(unsetDueDate)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

