/*
 * Gitea API
 * This documentation describes the Gitea API.
 *
 * OpenAPI spec version: 1.25.4
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.gitea.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * EditLabelOption options for editing a label
 */
@ApiModel(description = "EditLabelOption options for editing a label")

public class EditLabelOption {
  @SerializedName("color")
  private String color = null;

  @SerializedName("description")
  private String description = null;

  @SerializedName("exclusive")
  private Boolean exclusive = null;

  @SerializedName("is_archived")
  private Boolean isArchived = null;

  @SerializedName("name")
  private String name = null;

  public EditLabelOption color(String color) {
    this.color = color;
    return this;
  }

   /**
   * Get color
   * @return color
  **/
  @ApiModelProperty(example = "#00aabb", value = "")
  public String getColor() {
    return color;
  }

  public void setColor(String color) {
    this.color = color;
  }

  public EditLabelOption description(String description) {
    this.description = description;
    return this;
  }

   /**
   * Description provides additional context about the label&#39;s purpose
   * @return description
  **/
  @ApiModelProperty(value = "Description provides additional context about the label's purpose")
  public String getDescription() {
    return description;
  }

  public void setDescription(String description) {
    this.description = description;
  }

  public EditLabelOption exclusive(Boolean exclusive) {
    this.exclusive = exclusive;
    return this;
  }

   /**
   * Get exclusive
   * @return exclusive
  **/
  @ApiModelProperty(example = "false", value = "")
  public Boolean isExclusive() {
    return exclusive;
  }

  public void setExclusive(Boolean exclusive) {
    this.exclusive = exclusive;
  }

  public EditLabelOption isArchived(Boolean isArchived) {
    this.isArchived = isArchived;
    return this;
  }

   /**
   * Get isArchived
   * @return isArchived
  **/
  @ApiModelProperty(example = "false", value = "")
  public Boolean isIsArchived() {
    return isArchived;
  }

  public void setIsArchived(Boolean isArchived) {
    this.isArchived = isArchived;
  }

  public EditLabelOption name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Name is the new display name for the label
   * @return name
  **/
  @ApiModelProperty(value = "Name is the new display name for the label")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    EditLabelOption editLabelOption = (EditLabelOption) o;
    return Objects.equals(this.color, editLabelOption.color) &&
        Objects.equals(this.description, editLabelOption.description) &&
        Objects.equals(this.exclusive, editLabelOption.exclusive) &&
        Objects.equals(this.isArchived, editLabelOption.isArchived) &&
        Objects.equals(this.name, editLabelOption.name);
  }

  @Override
  public int hashCode() {
    return Objects.hash(color, description, exclusive, isArchived, name);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class EditLabelOption {\n");
    
    sb.append("    color: ").append(toIndentedString(color)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    exclusive: ").append(toIndentedString(exclusive)).append("\n");
    sb.append("    isArchived: ").append(toIndentedString(isArchived)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

