/*
 * Gitea API
 * This documentation describes the Gitea API.
 *
 * OpenAPI spec version: 1.25.3
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.gitea.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * Email an email address belonging to a user
 */
@ApiModel(description = "Email an email address belonging to a user")

public class Email {
  @SerializedName("email")
  private String email = null;

  @SerializedName("primary")
  private Boolean primary = null;

  @SerializedName("user_id")
  private Long userId = null;

  @SerializedName("username")
  private String username = null;

  @SerializedName("verified")
  private Boolean verified = null;

  public Email email(String email) {
    this.email = email;
    return this;
  }

   /**
   * Get email
   * @return email
  **/
  @ApiModelProperty(value = "")
  public String getEmail() {
    return email;
  }

  public void setEmail(String email) {
    this.email = email;
  }

  public Email primary(Boolean primary) {
    this.primary = primary;
    return this;
  }

   /**
   * Whether this is the primary email address
   * @return primary
  **/
  @ApiModelProperty(value = "Whether this is the primary email address")
  public Boolean isPrimary() {
    return primary;
  }

  public void setPrimary(Boolean primary) {
    this.primary = primary;
  }

  public Email userId(Long userId) {
    this.userId = userId;
    return this;
  }

   /**
   * The unique identifier of the user who owns this email
   * @return userId
  **/
  @ApiModelProperty(value = "The unique identifier of the user who owns this email")
  public Long getUserId() {
    return userId;
  }

  public void setUserId(Long userId) {
    this.userId = userId;
  }

  public Email username(String username) {
    this.username = username;
    return this;
  }

   /**
   * username of the user
   * @return username
  **/
  @ApiModelProperty(value = "username of the user")
  public String getUsername() {
    return username;
  }

  public void setUsername(String username) {
    this.username = username;
  }

  public Email verified(Boolean verified) {
    this.verified = verified;
    return this;
  }

   /**
   * Whether the email address has been verified
   * @return verified
  **/
  @ApiModelProperty(value = "Whether the email address has been verified")
  public Boolean isVerified() {
    return verified;
  }

  public void setVerified(Boolean verified) {
    this.verified = verified;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Email email = (Email) o;
    return Objects.equals(this.email, email.email) &&
        Objects.equals(this.primary, email.primary) &&
        Objects.equals(this.userId, email.userId) &&
        Objects.equals(this.username, email.username) &&
        Objects.equals(this.verified, email.verified);
  }

  @Override
  public int hashCode() {
    return Objects.hash(email, primary, userId, username, verified);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Email {\n");
    
    sb.append("    email: ").append(toIndentedString(email)).append("\n");
    sb.append("    primary: ").append(toIndentedString(primary)).append("\n");
    sb.append("    userId: ").append(toIndentedString(userId)).append("\n");
    sb.append("    username: ").append(toIndentedString(username)).append("\n");
    sb.append("    verified: ").append(toIndentedString(verified)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

