/*
 * Gitea API
 * This documentation describes the Gitea API.
 *
 * OpenAPI spec version: 1.26.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.gitea.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * GitBlobResponse represents a git blob
 */
@ApiModel(description = "GitBlobResponse represents a git blob")

public class GitBlobResponse {
  @SerializedName("content")
  private String content = null;

  @SerializedName("encoding")
  private String encoding = null;

  @SerializedName("lfs_oid")
  private String lfsOid = null;

  @SerializedName("lfs_size")
  private Long lfsSize = null;

  @SerializedName("sha")
  private String sha = null;

  @SerializedName("size")
  private Long size = null;

  @SerializedName("url")
  private String url = null;

  public GitBlobResponse content(String content) {
    this.content = content;
    return this;
  }

   /**
   * The content of the git blob (may be base64 encoded)
   * @return content
  **/
  @ApiModelProperty(value = "The content of the git blob (may be base64 encoded)")
  public String getContent() {
    return content;
  }

  public void setContent(String content) {
    this.content = content;
  }

  public GitBlobResponse encoding(String encoding) {
    this.encoding = encoding;
    return this;
  }

   /**
   * The encoding used for the content (e.g., \&quot;base64\&quot;)
   * @return encoding
  **/
  @ApiModelProperty(value = "The encoding used for the content (e.g., \"base64\")")
  public String getEncoding() {
    return encoding;
  }

  public void setEncoding(String encoding) {
    this.encoding = encoding;
  }

  public GitBlobResponse lfsOid(String lfsOid) {
    this.lfsOid = lfsOid;
    return this;
  }

   /**
   * The LFS object ID if this blob is stored in LFS
   * @return lfsOid
  **/
  @ApiModelProperty(value = "The LFS object ID if this blob is stored in LFS")
  public String getLfsOid() {
    return lfsOid;
  }

  public void setLfsOid(String lfsOid) {
    this.lfsOid = lfsOid;
  }

  public GitBlobResponse lfsSize(Long lfsSize) {
    this.lfsSize = lfsSize;
    return this;
  }

   /**
   * The size of the LFS object if this blob is stored in LFS
   * @return lfsSize
  **/
  @ApiModelProperty(value = "The size of the LFS object if this blob is stored in LFS")
  public Long getLfsSize() {
    return lfsSize;
  }

  public void setLfsSize(Long lfsSize) {
    this.lfsSize = lfsSize;
  }

  public GitBlobResponse sha(String sha) {
    this.sha = sha;
    return this;
  }

   /**
   * The SHA hash of the git blob
   * @return sha
  **/
  @ApiModelProperty(value = "The SHA hash of the git blob")
  public String getSha() {
    return sha;
  }

  public void setSha(String sha) {
    this.sha = sha;
  }

  public GitBlobResponse size(Long size) {
    this.size = size;
    return this;
  }

   /**
   * The size of the git blob in bytes
   * @return size
  **/
  @ApiModelProperty(value = "The size of the git blob in bytes")
  public Long getSize() {
    return size;
  }

  public void setSize(Long size) {
    this.size = size;
  }

  public GitBlobResponse url(String url) {
    this.url = url;
    return this;
  }

   /**
   * The URL to access this git blob
   * @return url
  **/
  @ApiModelProperty(value = "The URL to access this git blob")
  public String getUrl() {
    return url;
  }

  public void setUrl(String url) {
    this.url = url;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    GitBlobResponse gitBlobResponse = (GitBlobResponse) o;
    return Objects.equals(this.content, gitBlobResponse.content) &&
        Objects.equals(this.encoding, gitBlobResponse.encoding) &&
        Objects.equals(this.lfsOid, gitBlobResponse.lfsOid) &&
        Objects.equals(this.lfsSize, gitBlobResponse.lfsSize) &&
        Objects.equals(this.sha, gitBlobResponse.sha) &&
        Objects.equals(this.size, gitBlobResponse.size) &&
        Objects.equals(this.url, gitBlobResponse.url);
  }

  @Override
  public int hashCode() {
    return Objects.hash(content, encoding, lfsOid, lfsSize, sha, size, url);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class GitBlobResponse {\n");
    
    sb.append("    content: ").append(toIndentedString(content)).append("\n");
    sb.append("    encoding: ").append(toIndentedString(encoding)).append("\n");
    sb.append("    lfsOid: ").append(toIndentedString(lfsOid)).append("\n");
    sb.append("    lfsSize: ").append(toIndentedString(lfsSize)).append("\n");
    sb.append("    sha: ").append(toIndentedString(sha)).append("\n");
    sb.append("    size: ").append(toIndentedString(size)).append("\n");
    sb.append("    url: ").append(toIndentedString(url)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

