/*
 * Gitea API
 * This documentation describes the Gitea API.
 *
 * OpenAPI spec version: 1.26.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.gitea.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * GitEntry represents a git tree
 */
@ApiModel(description = "GitEntry represents a git tree")

public class GitEntry {
  @SerializedName("mode")
  private String mode = null;

  @SerializedName("path")
  private String path = null;

  @SerializedName("sha")
  private String sha = null;

  @SerializedName("size")
  private Long size = null;

  @SerializedName("type")
  private String type = null;

  @SerializedName("url")
  private String url = null;

  public GitEntry mode(String mode) {
    this.mode = mode;
    return this;
  }

   /**
   * Mode is the file mode (permissions)
   * @return mode
  **/
  @ApiModelProperty(value = "Mode is the file mode (permissions)")
  public String getMode() {
    return mode;
  }

  public void setMode(String mode) {
    this.mode = mode;
  }

  public GitEntry path(String path) {
    this.path = path;
    return this;
  }

   /**
   * Path is the file or directory path
   * @return path
  **/
  @ApiModelProperty(value = "Path is the file or directory path")
  public String getPath() {
    return path;
  }

  public void setPath(String path) {
    this.path = path;
  }

  public GitEntry sha(String sha) {
    this.sha = sha;
    return this;
  }

   /**
   * SHA is the Git object SHA
   * @return sha
  **/
  @ApiModelProperty(value = "SHA is the Git object SHA")
  public String getSha() {
    return sha;
  }

  public void setSha(String sha) {
    this.sha = sha;
  }

  public GitEntry size(Long size) {
    this.size = size;
    return this;
  }

   /**
   * Size is the file size in bytes
   * @return size
  **/
  @ApiModelProperty(value = "Size is the file size in bytes")
  public Long getSize() {
    return size;
  }

  public void setSize(Long size) {
    this.size = size;
  }

  public GitEntry type(String type) {
    this.type = type;
    return this;
  }

   /**
   * Type indicates if this is a file, directory, or symlink
   * @return type
  **/
  @ApiModelProperty(value = "Type indicates if this is a file, directory, or symlink")
  public String getType() {
    return type;
  }

  public void setType(String type) {
    this.type = type;
  }

  public GitEntry url(String url) {
    this.url = url;
    return this;
  }

   /**
   * URL is the API URL for this tree entry
   * @return url
  **/
  @ApiModelProperty(value = "URL is the API URL for this tree entry")
  public String getUrl() {
    return url;
  }

  public void setUrl(String url) {
    this.url = url;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    GitEntry gitEntry = (GitEntry) o;
    return Objects.equals(this.mode, gitEntry.mode) &&
        Objects.equals(this.path, gitEntry.path) &&
        Objects.equals(this.sha, gitEntry.sha) &&
        Objects.equals(this.size, gitEntry.size) &&
        Objects.equals(this.type, gitEntry.type) &&
        Objects.equals(this.url, gitEntry.url);
  }

  @Override
  public int hashCode() {
    return Objects.hash(mode, path, sha, size, type, url);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class GitEntry {\n");
    
    sb.append("    mode: ").append(toIndentedString(mode)).append("\n");
    sb.append("    path: ").append(toIndentedString(path)).append("\n");
    sb.append("    sha: ").append(toIndentedString(sha)).append("\n");
    sb.append("    size: ").append(toIndentedString(size)).append("\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("    url: ").append(toIndentedString(url)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

