/*
 * Gitea API
 * This documentation describes the Gitea API.
 *
 * OpenAPI spec version: 1.25.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.gitea.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * LicensesInfo contains information about a License
 */
@ApiModel(description = "LicensesInfo contains information about a License")

public class LicenseTemplateInfo {
  @SerializedName("body")
  private String body = null;

  @SerializedName("implementation")
  private String implementation = null;

  @SerializedName("key")
  private String key = null;

  @SerializedName("name")
  private String name = null;

  @SerializedName("url")
  private String url = null;

  public LicenseTemplateInfo body(String body) {
    this.body = body;
    return this;
  }

   /**
   * Body contains the full text of the license
   * @return body
  **/
  @ApiModelProperty(value = "Body contains the full text of the license")
  public String getBody() {
    return body;
  }

  public void setBody(String body) {
    this.body = body;
  }

  public LicenseTemplateInfo implementation(String implementation) {
    this.implementation = implementation;
    return this;
  }

   /**
   * Implementation contains license implementation details
   * @return implementation
  **/
  @ApiModelProperty(value = "Implementation contains license implementation details")
  public String getImplementation() {
    return implementation;
  }

  public void setImplementation(String implementation) {
    this.implementation = implementation;
  }

  public LicenseTemplateInfo key(String key) {
    this.key = key;
    return this;
  }

   /**
   * Key is the unique identifier for the license template
   * @return key
  **/
  @ApiModelProperty(value = "Key is the unique identifier for the license template")
  public String getKey() {
    return key;
  }

  public void setKey(String key) {
    this.key = key;
  }

  public LicenseTemplateInfo name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Name is the display name of the license
   * @return name
  **/
  @ApiModelProperty(value = "Name is the display name of the license")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public LicenseTemplateInfo url(String url) {
    this.url = url;
    return this;
  }

   /**
   * URL is the reference URL for the license
   * @return url
  **/
  @ApiModelProperty(value = "URL is the reference URL for the license")
  public String getUrl() {
    return url;
  }

  public void setUrl(String url) {
    this.url = url;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    LicenseTemplateInfo licenseTemplateInfo = (LicenseTemplateInfo) o;
    return Objects.equals(this.body, licenseTemplateInfo.body) &&
        Objects.equals(this.implementation, licenseTemplateInfo.implementation) &&
        Objects.equals(this.key, licenseTemplateInfo.key) &&
        Objects.equals(this.name, licenseTemplateInfo.name) &&
        Objects.equals(this.url, licenseTemplateInfo.url);
  }

  @Override
  public int hashCode() {
    return Objects.hash(body, implementation, key, name, url);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class LicenseTemplateInfo {\n");
    
    sb.append("    body: ").append(toIndentedString(body)).append("\n");
    sb.append("    implementation: ").append(toIndentedString(implementation)).append("\n");
    sb.append("    key: ").append(toIndentedString(key)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    url: ").append(toIndentedString(url)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

