/*
 * Gitea API
 * This documentation describes the Gitea API.
 *
 * OpenAPI spec version: 1.25.4
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.gitea.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * MarkupOption markup options
 */
@ApiModel(description = "MarkupOption markup options")

public class MarkupOption {
  @SerializedName("Context")
  private String context = null;

  @SerializedName("FilePath")
  private String filePath = null;

  @SerializedName("Mode")
  private String mode = null;

  @SerializedName("Text")
  private String text = null;

  @SerializedName("Wiki")
  private Boolean wiki = null;

  public MarkupOption context(String context) {
    this.context = context;
    return this;
  }

   /**
   * URL path for rendering issue, media and file links Expected format: /subpath/{user}/{repo}/src/{branch, commit, tag}/{identifier/path}/{file/dir}  in: body
   * @return context
  **/
  @ApiModelProperty(value = "URL path for rendering issue, media and file links Expected format: /subpath/{user}/{repo}/src/{branch, commit, tag}/{identifier/path}/{file/dir}  in: body")
  public String getContext() {
    return context;
  }

  public void setContext(String context) {
    this.context = context;
  }

  public MarkupOption filePath(String filePath) {
    this.filePath = filePath;
    return this;
  }

   /**
   * File path for detecting extension in file mode  in: body
   * @return filePath
  **/
  @ApiModelProperty(value = "File path for detecting extension in file mode  in: body")
  public String getFilePath() {
    return filePath;
  }

  public void setFilePath(String filePath) {
    this.filePath = filePath;
  }

  public MarkupOption mode(String mode) {
    this.mode = mode;
    return this;
  }

   /**
   * Mode to render (markdown, comment, wiki, file)  in: body
   * @return mode
  **/
  @ApiModelProperty(value = "Mode to render (markdown, comment, wiki, file)  in: body")
  public String getMode() {
    return mode;
  }

  public void setMode(String mode) {
    this.mode = mode;
  }

  public MarkupOption text(String text) {
    this.text = text;
    return this;
  }

   /**
   * Text markup to render  in: body
   * @return text
  **/
  @ApiModelProperty(value = "Text markup to render  in: body")
  public String getText() {
    return text;
  }

  public void setText(String text) {
    this.text = text;
  }

  public MarkupOption wiki(Boolean wiki) {
    this.wiki = wiki;
    return this;
  }

   /**
   * Is it a wiki page? (use mode&#x3D;wiki instead)  Deprecated: true in: body
   * @return wiki
  **/
  @ApiModelProperty(value = "Is it a wiki page? (use mode=wiki instead)  Deprecated: true in: body")
  public Boolean isWiki() {
    return wiki;
  }

  public void setWiki(Boolean wiki) {
    this.wiki = wiki;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    MarkupOption markupOption = (MarkupOption) o;
    return Objects.equals(this.context, markupOption.context) &&
        Objects.equals(this.filePath, markupOption.filePath) &&
        Objects.equals(this.mode, markupOption.mode) &&
        Objects.equals(this.text, markupOption.text) &&
        Objects.equals(this.wiki, markupOption.wiki);
  }

  @Override
  public int hashCode() {
    return Objects.hash(context, filePath, mode, text, wiki);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class MarkupOption {\n");
    
    sb.append("    context: ").append(toIndentedString(context)).append("\n");
    sb.append("    filePath: ").append(toIndentedString(filePath)).append("\n");
    sb.append("    mode: ").append(toIndentedString(mode)).append("\n");
    sb.append("    text: ").append(toIndentedString(text)).append("\n");
    sb.append("    wiki: ").append(toIndentedString(wiki)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

