/*
 * Gitea API
 * This documentation describes the Gitea API.
 *
 * OpenAPI spec version: 28.1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.gitea.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * MoveProjectIssueOption represents options for moving an issue between columns
 */
@ApiModel(description = "MoveProjectIssueOption represents options for moving an issue between columns")

public class MoveProjectIssueOption {
  @SerializedName("column_id")
  private Long columnId = null;

  @SerializedName("sorting")
  private Long sorting = null;

  public MoveProjectIssueOption columnId(Long columnId) {
    this.columnId = columnId;
    return this;
  }

   /**
   * Target column to move the issue into
   * @return columnId
  **/
  @ApiModelProperty(required = true, value = "Target column to move the issue into")
  public Long getColumnId() {
    return columnId;
  }

  public void setColumnId(Long columnId) {
    this.columnId = columnId;
  }

  public MoveProjectIssueOption sorting(Long sorting) {
    this.sorting = sorting;
    return this;
  }

   /**
   * Position within the column, ascending. Omit to append. Negative values sort above the rest, equal values are ordered newest first.
   * @return sorting
  **/
  @ApiModelProperty(value = "Position within the column, ascending. Omit to append. Negative values sort above the rest, equal values are ordered newest first.")
  public Long getSorting() {
    return sorting;
  }

  public void setSorting(Long sorting) {
    this.sorting = sorting;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    MoveProjectIssueOption moveProjectIssueOption = (MoveProjectIssueOption) o;
    return Objects.equals(this.columnId, moveProjectIssueOption.columnId) &&
        Objects.equals(this.sorting, moveProjectIssueOption.sorting);
  }

  @Override
  public int hashCode() {
    return Objects.hash(columnId, sorting);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class MoveProjectIssueOption {\n");
    
    sb.append("    columnId: ").append(toIndentedString(columnId)).append("\n");
    sb.append("    sorting: ").append(toIndentedString(sorting)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

