/*
 * Gitea API
 * This documentation describes the Gitea API.
 *
 * OpenAPI spec version: 28.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.gitea.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * MoveProjectColumnsOption represents options for reordering a project&#39;s columns
 */
@ApiModel(description = "MoveProjectColumnsOption represents options for reordering a project's columns")

public class MoveProjectColumnsOption {
  @SerializedName("column_ids")
  private List<Long> columnIds = new ArrayList<Long>();

  public MoveProjectColumnsOption columnIds(List<Long> columnIds) {
    this.columnIds = columnIds;
    return this;
  }

  public MoveProjectColumnsOption addColumnIdsItem(Long columnIdsItem) {
    this.columnIds.add(columnIdsItem);
    return this;
  }

   /**
   * Every column ID of the project, in the desired left-to-right order
   * @return columnIds
  **/
  @ApiModelProperty(required = true, value = "Every column ID of the project, in the desired left-to-right order")
  public List<Long> getColumnIds() {
    return columnIds;
  }

  public void setColumnIds(List<Long> columnIds) {
    this.columnIds = columnIds;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    MoveProjectColumnsOption moveProjectColumnsOption = (MoveProjectColumnsOption) o;
    return Objects.equals(this.columnIds, moveProjectColumnsOption.columnIds);
  }

  @Override
  public int hashCode() {
    return Objects.hash(columnIds);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class MoveProjectColumnsOption {\n");
    
    sb.append("    columnIds: ").append(toIndentedString(columnIds)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

