/*
 * Gitea API
 * This documentation describes the Gitea API.
 *
 * OpenAPI spec version: 1.25.5
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.gitea.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * NodeInfoSoftware contains Metadata about server software in use
 */
@ApiModel(description = "NodeInfoSoftware contains Metadata about server software in use")

public class NodeInfoSoftware {
  @SerializedName("homepage")
  private String homepage = null;

  @SerializedName("name")
  private String name = null;

  @SerializedName("repository")
  private String repository = null;

  @SerializedName("version")
  private String version = null;

  public NodeInfoSoftware homepage(String homepage) {
    this.homepage = homepage;
    return this;
  }

   /**
   * Homepage is the URL to the homepage of this server software
   * @return homepage
  **/
  @ApiModelProperty(value = "Homepage is the URL to the homepage of this server software")
  public String getHomepage() {
    return homepage;
  }

  public void setHomepage(String homepage) {
    this.homepage = homepage;
  }

  public NodeInfoSoftware name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Name is the canonical name of this server software
   * @return name
  **/
  @ApiModelProperty(value = "Name is the canonical name of this server software")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public NodeInfoSoftware repository(String repository) {
    this.repository = repository;
    return this;
  }

   /**
   * Repository is the URL to the source code repository
   * @return repository
  **/
  @ApiModelProperty(value = "Repository is the URL to the source code repository")
  public String getRepository() {
    return repository;
  }

  public void setRepository(String repository) {
    this.repository = repository;
  }

  public NodeInfoSoftware version(String version) {
    this.version = version;
    return this;
  }

   /**
   * Version is the version of this server software
   * @return version
  **/
  @ApiModelProperty(value = "Version is the version of this server software")
  public String getVersion() {
    return version;
  }

  public void setVersion(String version) {
    this.version = version;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    NodeInfoSoftware nodeInfoSoftware = (NodeInfoSoftware) o;
    return Objects.equals(this.homepage, nodeInfoSoftware.homepage) &&
        Objects.equals(this.name, nodeInfoSoftware.name) &&
        Objects.equals(this.repository, nodeInfoSoftware.repository) &&
        Objects.equals(this.version, nodeInfoSoftware.version);
  }

  @Override
  public int hashCode() {
    return Objects.hash(homepage, name, repository, version);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class NodeInfoSoftware {\n");
    
    sb.append("    homepage: ").append(toIndentedString(homepage)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    repository: ").append(toIndentedString(repository)).append("\n");
    sb.append("    version: ").append(toIndentedString(version)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

