/*
 * Gitea API
 * This documentation describes the Gitea API.
 *
 * OpenAPI spec version: 1.26.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.gitea.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * NotificationSubject contains the notification subject (Issue/Pull/Commit)
 */
@ApiModel(description = "NotificationSubject contains the notification subject (Issue/Pull/Commit)")

public class NotificationSubject {
  @SerializedName("html_url")
  private String htmlUrl = null;

  @SerializedName("latest_comment_html_url")
  private String latestCommentHtmlUrl = null;

  @SerializedName("latest_comment_url")
  private String latestCommentUrl = null;

  /**
   * State indicates the current state of the notification subject open NotifySubjectStateOpen  NotifySubjectStateOpen is an open subject closed NotifySubjectStateClosed  NotifySubjectStateClosed is a closed subject merged NotifySubjectStateMerged  NotifySubjectStateMerged is a merged pull request
   */
  @JsonAdapter(StateEnum.Adapter.class)
  public enum StateEnum {
    OPEN("open"),
    
    CLOSED("closed"),
    
    MERGED("merged");

    private String value;

    StateEnum(String value) {
      this.value = value;
    }

    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    public static StateEnum fromValue(String text) {
      for (StateEnum b : StateEnum.values()) {
        if (String.valueOf(b.value).equals(text)) {
          return b;
        }
      }
      return null;
    }

    public static class Adapter extends TypeAdapter<StateEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final StateEnum enumeration) throws IOException {
        jsonWriter.value(enumeration.getValue());
      }

      @Override
      public StateEnum read(final JsonReader jsonReader) throws IOException {
        String value = jsonReader.nextString();
        return StateEnum.fromValue(String.valueOf(value));
      }
    }
  }

  @SerializedName("state")
  private StateEnum state = null;

  @SerializedName("title")
  private String title = null;

  /**
   * Type indicates the type of the notification subject Issue NotifySubjectIssue  NotifySubjectIssue an issue is subject of an notification Pull NotifySubjectPull  NotifySubjectPull an pull is subject of an notification Commit NotifySubjectCommit  NotifySubjectCommit an commit is subject of an notification Repository NotifySubjectRepository  NotifySubjectRepository an repository is subject of an notification
   */
  @JsonAdapter(TypeEnum.Adapter.class)
  public enum TypeEnum {
    ISSUE("Issue"),
    
    PULL("Pull"),
    
    COMMIT("Commit"),
    
    REPOSITORY("Repository");

    private String value;

    TypeEnum(String value) {
      this.value = value;
    }

    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    public static TypeEnum fromValue(String text) {
      for (TypeEnum b : TypeEnum.values()) {
        if (String.valueOf(b.value).equals(text)) {
          return b;
        }
      }
      return null;
    }

    public static class Adapter extends TypeAdapter<TypeEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final TypeEnum enumeration) throws IOException {
        jsonWriter.value(enumeration.getValue());
      }

      @Override
      public TypeEnum read(final JsonReader jsonReader) throws IOException {
        String value = jsonReader.nextString();
        return TypeEnum.fromValue(String.valueOf(value));
      }
    }
  }

  @SerializedName("type")
  private TypeEnum type = null;

  @SerializedName("url")
  private String url = null;

  public NotificationSubject htmlUrl(String htmlUrl) {
    this.htmlUrl = htmlUrl;
    return this;
  }

   /**
   * HTMLURL is the web URL for the notification subject
   * @return htmlUrl
  **/
  @ApiModelProperty(value = "HTMLURL is the web URL for the notification subject")
  public String getHtmlUrl() {
    return htmlUrl;
  }

  public void setHtmlUrl(String htmlUrl) {
    this.htmlUrl = htmlUrl;
  }

  public NotificationSubject latestCommentHtmlUrl(String latestCommentHtmlUrl) {
    this.latestCommentHtmlUrl = latestCommentHtmlUrl;
    return this;
  }

   /**
   * LatestCommentHTMLURL is the web URL for the latest comment
   * @return latestCommentHtmlUrl
  **/
  @ApiModelProperty(value = "LatestCommentHTMLURL is the web URL for the latest comment")
  public String getLatestCommentHtmlUrl() {
    return latestCommentHtmlUrl;
  }

  public void setLatestCommentHtmlUrl(String latestCommentHtmlUrl) {
    this.latestCommentHtmlUrl = latestCommentHtmlUrl;
  }

  public NotificationSubject latestCommentUrl(String latestCommentUrl) {
    this.latestCommentUrl = latestCommentUrl;
    return this;
  }

   /**
   * LatestCommentURL is the API URL for the latest comment
   * @return latestCommentUrl
  **/
  @ApiModelProperty(value = "LatestCommentURL is the API URL for the latest comment")
  public String getLatestCommentUrl() {
    return latestCommentUrl;
  }

  public void setLatestCommentUrl(String latestCommentUrl) {
    this.latestCommentUrl = latestCommentUrl;
  }

  public NotificationSubject state(StateEnum state) {
    this.state = state;
    return this;
  }

   /**
   * State indicates the current state of the notification subject open NotifySubjectStateOpen  NotifySubjectStateOpen is an open subject closed NotifySubjectStateClosed  NotifySubjectStateClosed is a closed subject merged NotifySubjectStateMerged  NotifySubjectStateMerged is a merged pull request
   * @return state
  **/
  @ApiModelProperty(value = "State indicates the current state of the notification subject open NotifySubjectStateOpen  NotifySubjectStateOpen is an open subject closed NotifySubjectStateClosed  NotifySubjectStateClosed is a closed subject merged NotifySubjectStateMerged  NotifySubjectStateMerged is a merged pull request")
  public StateEnum getState() {
    return state;
  }

  public void setState(StateEnum state) {
    this.state = state;
  }

  public NotificationSubject title(String title) {
    this.title = title;
    return this;
  }

   /**
   * Title is the title of the notification subject
   * @return title
  **/
  @ApiModelProperty(value = "Title is the title of the notification subject")
  public String getTitle() {
    return title;
  }

  public void setTitle(String title) {
    this.title = title;
  }

  public NotificationSubject type(TypeEnum type) {
    this.type = type;
    return this;
  }

   /**
   * Type indicates the type of the notification subject Issue NotifySubjectIssue  NotifySubjectIssue an issue is subject of an notification Pull NotifySubjectPull  NotifySubjectPull an pull is subject of an notification Commit NotifySubjectCommit  NotifySubjectCommit an commit is subject of an notification Repository NotifySubjectRepository  NotifySubjectRepository an repository is subject of an notification
   * @return type
  **/
  @ApiModelProperty(value = "Type indicates the type of the notification subject Issue NotifySubjectIssue  NotifySubjectIssue an issue is subject of an notification Pull NotifySubjectPull  NotifySubjectPull an pull is subject of an notification Commit NotifySubjectCommit  NotifySubjectCommit an commit is subject of an notification Repository NotifySubjectRepository  NotifySubjectRepository an repository is subject of an notification")
  public TypeEnum getType() {
    return type;
  }

  public void setType(TypeEnum type) {
    this.type = type;
  }

  public NotificationSubject url(String url) {
    this.url = url;
    return this;
  }

   /**
   * URL is the API URL for the notification subject
   * @return url
  **/
  @ApiModelProperty(value = "URL is the API URL for the notification subject")
  public String getUrl() {
    return url;
  }

  public void setUrl(String url) {
    this.url = url;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    NotificationSubject notificationSubject = (NotificationSubject) o;
    return Objects.equals(this.htmlUrl, notificationSubject.htmlUrl) &&
        Objects.equals(this.latestCommentHtmlUrl, notificationSubject.latestCommentHtmlUrl) &&
        Objects.equals(this.latestCommentUrl, notificationSubject.latestCommentUrl) &&
        Objects.equals(this.state, notificationSubject.state) &&
        Objects.equals(this.title, notificationSubject.title) &&
        Objects.equals(this.type, notificationSubject.type) &&
        Objects.equals(this.url, notificationSubject.url);
  }

  @Override
  public int hashCode() {
    return Objects.hash(htmlUrl, latestCommentHtmlUrl, latestCommentUrl, state, title, type, url);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class NotificationSubject {\n");
    
    sb.append("    htmlUrl: ").append(toIndentedString(htmlUrl)).append("\n");
    sb.append("    latestCommentHtmlUrl: ").append(toIndentedString(latestCommentHtmlUrl)).append("\n");
    sb.append("    latestCommentUrl: ").append(toIndentedString(latestCommentUrl)).append("\n");
    sb.append("    state: ").append(toIndentedString(state)).append("\n");
    sb.append("    title: ").append(toIndentedString(title)).append("\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("    url: ").append(toIndentedString(url)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

