/*
 * Gitea API
 * This documentation describes the Gitea API.
 *
 * OpenAPI spec version: 1.25.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.gitea.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.gitea.model.Label;
import io.gitea.model.Milestone;
import io.gitea.model.PRBranchInfo;
import io.gitea.model.Team;
import io.gitea.model.User;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.threeten.bp.OffsetDateTime;

/**
 * PullRequest represents a pull request
 */
@ApiModel(description = "PullRequest represents a pull request")

public class PullRequest {
  @SerializedName("additions")
  private Long additions = null;

  @SerializedName("allow_maintainer_edit")
  private Boolean allowMaintainerEdit = null;

  @SerializedName("assignee")
  private User assignee = null;

  @SerializedName("assignees")
  private List<User> assignees = null;

  @SerializedName("base")
  private PRBranchInfo base = null;

  @SerializedName("body")
  private String body = null;

  @SerializedName("changed_files")
  private Long changedFiles = null;

  @SerializedName("closed_at")
  private OffsetDateTime closedAt = null;

  @SerializedName("comments")
  private Long comments = null;

  @SerializedName("created_at")
  private OffsetDateTime createdAt = null;

  @SerializedName("deletions")
  private Long deletions = null;

  @SerializedName("diff_url")
  private String diffUrl = null;

  @SerializedName("draft")
  private Boolean draft = null;

  @SerializedName("due_date")
  private OffsetDateTime dueDate = null;

  @SerializedName("head")
  private PRBranchInfo head = null;

  @SerializedName("html_url")
  private String htmlUrl = null;

  @SerializedName("id")
  private Long id = null;

  @SerializedName("is_locked")
  private Boolean isLocked = null;

  @SerializedName("labels")
  private List<Label> labels = null;

  @SerializedName("merge_base")
  private String mergeBase = null;

  @SerializedName("merge_commit_sha")
  private String mergeCommitSha = null;

  @SerializedName("mergeable")
  private Boolean mergeable = null;

  @SerializedName("merged")
  private Boolean merged = null;

  @SerializedName("merged_at")
  private OffsetDateTime mergedAt = null;

  @SerializedName("merged_by")
  private User mergedBy = null;

  @SerializedName("milestone")
  private Milestone milestone = null;

  @SerializedName("number")
  private Long number = null;

  @SerializedName("patch_url")
  private String patchUrl = null;

  @SerializedName("pin_order")
  private Long pinOrder = null;

  @SerializedName("requested_reviewers")
  private List<User> requestedReviewers = null;

  @SerializedName("requested_reviewers_teams")
  private List<Team> requestedReviewersTeams = null;

  @SerializedName("review_comments")
  private Long reviewComments = null;

  @SerializedName("state")
  private String state = null;

  @SerializedName("title")
  private String title = null;

  @SerializedName("updated_at")
  private OffsetDateTime updatedAt = null;

  @SerializedName("url")
  private String url = null;

  @SerializedName("user")
  private User user = null;

  public PullRequest additions(Long additions) {
    this.additions = additions;
    return this;
  }

   /**
   * The number of lines added in the pull request
   * @return additions
  **/
  @ApiModelProperty(value = "The number of lines added in the pull request")
  public Long getAdditions() {
    return additions;
  }

  public void setAdditions(Long additions) {
    this.additions = additions;
  }

  public PullRequest allowMaintainerEdit(Boolean allowMaintainerEdit) {
    this.allowMaintainerEdit = allowMaintainerEdit;
    return this;
  }

   /**
   * Whether maintainers can edit the pull request
   * @return allowMaintainerEdit
  **/
  @ApiModelProperty(value = "Whether maintainers can edit the pull request")
  public Boolean isAllowMaintainerEdit() {
    return allowMaintainerEdit;
  }

  public void setAllowMaintainerEdit(Boolean allowMaintainerEdit) {
    this.allowMaintainerEdit = allowMaintainerEdit;
  }

  public PullRequest assignee(User assignee) {
    this.assignee = assignee;
    return this;
  }

   /**
   * Get assignee
   * @return assignee
  **/
  @ApiModelProperty(value = "")
  public User getAssignee() {
    return assignee;
  }

  public void setAssignee(User assignee) {
    this.assignee = assignee;
  }

  public PullRequest assignees(List<User> assignees) {
    this.assignees = assignees;
    return this;
  }

  public PullRequest addAssigneesItem(User assigneesItem) {
    if (this.assignees == null) {
      this.assignees = new ArrayList<User>();
    }
    this.assignees.add(assigneesItem);
    return this;
  }

   /**
   * The list of users assigned to the pull request
   * @return assignees
  **/
  @ApiModelProperty(value = "The list of users assigned to the pull request")
  public List<User> getAssignees() {
    return assignees;
  }

  public void setAssignees(List<User> assignees) {
    this.assignees = assignees;
  }

  public PullRequest base(PRBranchInfo base) {
    this.base = base;
    return this;
  }

   /**
   * Get base
   * @return base
  **/
  @ApiModelProperty(value = "")
  public PRBranchInfo getBase() {
    return base;
  }

  public void setBase(PRBranchInfo base) {
    this.base = base;
  }

  public PullRequest body(String body) {
    this.body = body;
    return this;
  }

   /**
   * The description body of the pull request
   * @return body
  **/
  @ApiModelProperty(value = "The description body of the pull request")
  public String getBody() {
    return body;
  }

  public void setBody(String body) {
    this.body = body;
  }

  public PullRequest changedFiles(Long changedFiles) {
    this.changedFiles = changedFiles;
    return this;
  }

   /**
   * The number of files changed in the pull request
   * @return changedFiles
  **/
  @ApiModelProperty(value = "The number of files changed in the pull request")
  public Long getChangedFiles() {
    return changedFiles;
  }

  public void setChangedFiles(Long changedFiles) {
    this.changedFiles = changedFiles;
  }

  public PullRequest closedAt(OffsetDateTime closedAt) {
    this.closedAt = closedAt;
    return this;
  }

   /**
   * Get closedAt
   * @return closedAt
  **/
  @ApiModelProperty(value = "")
  public OffsetDateTime getClosedAt() {
    return closedAt;
  }

  public void setClosedAt(OffsetDateTime closedAt) {
    this.closedAt = closedAt;
  }

  public PullRequest comments(Long comments) {
    this.comments = comments;
    return this;
  }

   /**
   * The number of comments on the pull request
   * @return comments
  **/
  @ApiModelProperty(value = "The number of comments on the pull request")
  public Long getComments() {
    return comments;
  }

  public void setComments(Long comments) {
    this.comments = comments;
  }

  public PullRequest createdAt(OffsetDateTime createdAt) {
    this.createdAt = createdAt;
    return this;
  }

   /**
   * Get createdAt
   * @return createdAt
  **/
  @ApiModelProperty(value = "")
  public OffsetDateTime getCreatedAt() {
    return createdAt;
  }

  public void setCreatedAt(OffsetDateTime createdAt) {
    this.createdAt = createdAt;
  }

  public PullRequest deletions(Long deletions) {
    this.deletions = deletions;
    return this;
  }

   /**
   * The number of lines deleted in the pull request
   * @return deletions
  **/
  @ApiModelProperty(value = "The number of lines deleted in the pull request")
  public Long getDeletions() {
    return deletions;
  }

  public void setDeletions(Long deletions) {
    this.deletions = deletions;
  }

  public PullRequest diffUrl(String diffUrl) {
    this.diffUrl = diffUrl;
    return this;
  }

   /**
   * The URL to download the diff patch
   * @return diffUrl
  **/
  @ApiModelProperty(value = "The URL to download the diff patch")
  public String getDiffUrl() {
    return diffUrl;
  }

  public void setDiffUrl(String diffUrl) {
    this.diffUrl = diffUrl;
  }

  public PullRequest draft(Boolean draft) {
    this.draft = draft;
    return this;
  }

   /**
   * Whether the pull request is a draft
   * @return draft
  **/
  @ApiModelProperty(value = "Whether the pull request is a draft")
  public Boolean isDraft() {
    return draft;
  }

  public void setDraft(Boolean draft) {
    this.draft = draft;
  }

  public PullRequest dueDate(OffsetDateTime dueDate) {
    this.dueDate = dueDate;
    return this;
  }

   /**
   * Get dueDate
   * @return dueDate
  **/
  @ApiModelProperty(value = "")
  public OffsetDateTime getDueDate() {
    return dueDate;
  }

  public void setDueDate(OffsetDateTime dueDate) {
    this.dueDate = dueDate;
  }

  public PullRequest head(PRBranchInfo head) {
    this.head = head;
    return this;
  }

   /**
   * Get head
   * @return head
  **/
  @ApiModelProperty(value = "")
  public PRBranchInfo getHead() {
    return head;
  }

  public void setHead(PRBranchInfo head) {
    this.head = head;
  }

  public PullRequest htmlUrl(String htmlUrl) {
    this.htmlUrl = htmlUrl;
    return this;
  }

   /**
   * The HTML URL to view the pull request
   * @return htmlUrl
  **/
  @ApiModelProperty(value = "The HTML URL to view the pull request")
  public String getHtmlUrl() {
    return htmlUrl;
  }

  public void setHtmlUrl(String htmlUrl) {
    this.htmlUrl = htmlUrl;
  }

  public PullRequest id(Long id) {
    this.id = id;
    return this;
  }

   /**
   * The unique identifier of the pull request
   * @return id
  **/
  @ApiModelProperty(value = "The unique identifier of the pull request")
  public Long getId() {
    return id;
  }

  public void setId(Long id) {
    this.id = id;
  }

  public PullRequest isLocked(Boolean isLocked) {
    this.isLocked = isLocked;
    return this;
  }

   /**
   * Whether the pull request conversation is locked
   * @return isLocked
  **/
  @ApiModelProperty(value = "Whether the pull request conversation is locked")
  public Boolean isIsLocked() {
    return isLocked;
  }

  public void setIsLocked(Boolean isLocked) {
    this.isLocked = isLocked;
  }

  public PullRequest labels(List<Label> labels) {
    this.labels = labels;
    return this;
  }

  public PullRequest addLabelsItem(Label labelsItem) {
    if (this.labels == null) {
      this.labels = new ArrayList<Label>();
    }
    this.labels.add(labelsItem);
    return this;
  }

   /**
   * The labels attached to the pull request
   * @return labels
  **/
  @ApiModelProperty(value = "The labels attached to the pull request")
  public List<Label> getLabels() {
    return labels;
  }

  public void setLabels(List<Label> labels) {
    this.labels = labels;
  }

  public PullRequest mergeBase(String mergeBase) {
    this.mergeBase = mergeBase;
    return this;
  }

   /**
   * The merge base commit SHA
   * @return mergeBase
  **/
  @ApiModelProperty(value = "The merge base commit SHA")
  public String getMergeBase() {
    return mergeBase;
  }

  public void setMergeBase(String mergeBase) {
    this.mergeBase = mergeBase;
  }

  public PullRequest mergeCommitSha(String mergeCommitSha) {
    this.mergeCommitSha = mergeCommitSha;
    return this;
  }

   /**
   * The SHA of the merge commit
   * @return mergeCommitSha
  **/
  @ApiModelProperty(value = "The SHA of the merge commit")
  public String getMergeCommitSha() {
    return mergeCommitSha;
  }

  public void setMergeCommitSha(String mergeCommitSha) {
    this.mergeCommitSha = mergeCommitSha;
  }

  public PullRequest mergeable(Boolean mergeable) {
    this.mergeable = mergeable;
    return this;
  }

   /**
   * Whether the pull request can be merged
   * @return mergeable
  **/
  @ApiModelProperty(value = "Whether the pull request can be merged")
  public Boolean isMergeable() {
    return mergeable;
  }

  public void setMergeable(Boolean mergeable) {
    this.mergeable = mergeable;
  }

  public PullRequest merged(Boolean merged) {
    this.merged = merged;
    return this;
  }

   /**
   * Whether the pull request has been merged
   * @return merged
  **/
  @ApiModelProperty(value = "Whether the pull request has been merged")
  public Boolean isMerged() {
    return merged;
  }

  public void setMerged(Boolean merged) {
    this.merged = merged;
  }

  public PullRequest mergedAt(OffsetDateTime mergedAt) {
    this.mergedAt = mergedAt;
    return this;
  }

   /**
   * Get mergedAt
   * @return mergedAt
  **/
  @ApiModelProperty(value = "")
  public OffsetDateTime getMergedAt() {
    return mergedAt;
  }

  public void setMergedAt(OffsetDateTime mergedAt) {
    this.mergedAt = mergedAt;
  }

  public PullRequest mergedBy(User mergedBy) {
    this.mergedBy = mergedBy;
    return this;
  }

   /**
   * Get mergedBy
   * @return mergedBy
  **/
  @ApiModelProperty(value = "")
  public User getMergedBy() {
    return mergedBy;
  }

  public void setMergedBy(User mergedBy) {
    this.mergedBy = mergedBy;
  }

  public PullRequest milestone(Milestone milestone) {
    this.milestone = milestone;
    return this;
  }

   /**
   * Get milestone
   * @return milestone
  **/
  @ApiModelProperty(value = "")
  public Milestone getMilestone() {
    return milestone;
  }

  public void setMilestone(Milestone milestone) {
    this.milestone = milestone;
  }

  public PullRequest number(Long number) {
    this.number = number;
    return this;
  }

   /**
   * The pull request number
   * @return number
  **/
  @ApiModelProperty(value = "The pull request number")
  public Long getNumber() {
    return number;
  }

  public void setNumber(Long number) {
    this.number = number;
  }

  public PullRequest patchUrl(String patchUrl) {
    this.patchUrl = patchUrl;
    return this;
  }

   /**
   * The URL to download the patch file
   * @return patchUrl
  **/
  @ApiModelProperty(value = "The URL to download the patch file")
  public String getPatchUrl() {
    return patchUrl;
  }

  public void setPatchUrl(String patchUrl) {
    this.patchUrl = patchUrl;
  }

  public PullRequest pinOrder(Long pinOrder) {
    this.pinOrder = pinOrder;
    return this;
  }

   /**
   * The pin order for the pull request
   * @return pinOrder
  **/
  @ApiModelProperty(value = "The pin order for the pull request")
  public Long getPinOrder() {
    return pinOrder;
  }

  public void setPinOrder(Long pinOrder) {
    this.pinOrder = pinOrder;
  }

  public PullRequest requestedReviewers(List<User> requestedReviewers) {
    this.requestedReviewers = requestedReviewers;
    return this;
  }

  public PullRequest addRequestedReviewersItem(User requestedReviewersItem) {
    if (this.requestedReviewers == null) {
      this.requestedReviewers = new ArrayList<User>();
    }
    this.requestedReviewers.add(requestedReviewersItem);
    return this;
  }

   /**
   * The users requested to review the pull request
   * @return requestedReviewers
  **/
  @ApiModelProperty(value = "The users requested to review the pull request")
  public List<User> getRequestedReviewers() {
    return requestedReviewers;
  }

  public void setRequestedReviewers(List<User> requestedReviewers) {
    this.requestedReviewers = requestedReviewers;
  }

  public PullRequest requestedReviewersTeams(List<Team> requestedReviewersTeams) {
    this.requestedReviewersTeams = requestedReviewersTeams;
    return this;
  }

  public PullRequest addRequestedReviewersTeamsItem(Team requestedReviewersTeamsItem) {
    if (this.requestedReviewersTeams == null) {
      this.requestedReviewersTeams = new ArrayList<Team>();
    }
    this.requestedReviewersTeams.add(requestedReviewersTeamsItem);
    return this;
  }

   /**
   * The teams requested to review the pull request
   * @return requestedReviewersTeams
  **/
  @ApiModelProperty(value = "The teams requested to review the pull request")
  public List<Team> getRequestedReviewersTeams() {
    return requestedReviewersTeams;
  }

  public void setRequestedReviewersTeams(List<Team> requestedReviewersTeams) {
    this.requestedReviewersTeams = requestedReviewersTeams;
  }

  public PullRequest reviewComments(Long reviewComments) {
    this.reviewComments = reviewComments;
    return this;
  }

   /**
   * number of review comments made on the diff of a PR review (not including comments on commits or issues in a PR)
   * @return reviewComments
  **/
  @ApiModelProperty(value = "number of review comments made on the diff of a PR review (not including comments on commits or issues in a PR)")
  public Long getReviewComments() {
    return reviewComments;
  }

  public void setReviewComments(Long reviewComments) {
    this.reviewComments = reviewComments;
  }

  public PullRequest state(String state) {
    this.state = state;
    return this;
  }

   /**
   * Get state
   * @return state
  **/
  @ApiModelProperty(value = "")
  public String getState() {
    return state;
  }

  public void setState(String state) {
    this.state = state;
  }

  public PullRequest title(String title) {
    this.title = title;
    return this;
  }

   /**
   * The title of the pull request
   * @return title
  **/
  @ApiModelProperty(value = "The title of the pull request")
  public String getTitle() {
    return title;
  }

  public void setTitle(String title) {
    this.title = title;
  }

  public PullRequest updatedAt(OffsetDateTime updatedAt) {
    this.updatedAt = updatedAt;
    return this;
  }

   /**
   * Get updatedAt
   * @return updatedAt
  **/
  @ApiModelProperty(value = "")
  public OffsetDateTime getUpdatedAt() {
    return updatedAt;
  }

  public void setUpdatedAt(OffsetDateTime updatedAt) {
    this.updatedAt = updatedAt;
  }

  public PullRequest url(String url) {
    this.url = url;
    return this;
  }

   /**
   * The API URL of the pull request
   * @return url
  **/
  @ApiModelProperty(value = "The API URL of the pull request")
  public String getUrl() {
    return url;
  }

  public void setUrl(String url) {
    this.url = url;
  }

  public PullRequest user(User user) {
    this.user = user;
    return this;
  }

   /**
   * Get user
   * @return user
  **/
  @ApiModelProperty(value = "")
  public User getUser() {
    return user;
  }

  public void setUser(User user) {
    this.user = user;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PullRequest pullRequest = (PullRequest) o;
    return Objects.equals(this.additions, pullRequest.additions) &&
        Objects.equals(this.allowMaintainerEdit, pullRequest.allowMaintainerEdit) &&
        Objects.equals(this.assignee, pullRequest.assignee) &&
        Objects.equals(this.assignees, pullRequest.assignees) &&
        Objects.equals(this.base, pullRequest.base) &&
        Objects.equals(this.body, pullRequest.body) &&
        Objects.equals(this.changedFiles, pullRequest.changedFiles) &&
        Objects.equals(this.closedAt, pullRequest.closedAt) &&
        Objects.equals(this.comments, pullRequest.comments) &&
        Objects.equals(this.createdAt, pullRequest.createdAt) &&
        Objects.equals(this.deletions, pullRequest.deletions) &&
        Objects.equals(this.diffUrl, pullRequest.diffUrl) &&
        Objects.equals(this.draft, pullRequest.draft) &&
        Objects.equals(this.dueDate, pullRequest.dueDate) &&
        Objects.equals(this.head, pullRequest.head) &&
        Objects.equals(this.htmlUrl, pullRequest.htmlUrl) &&
        Objects.equals(this.id, pullRequest.id) &&
        Objects.equals(this.isLocked, pullRequest.isLocked) &&
        Objects.equals(this.labels, pullRequest.labels) &&
        Objects.equals(this.mergeBase, pullRequest.mergeBase) &&
        Objects.equals(this.mergeCommitSha, pullRequest.mergeCommitSha) &&
        Objects.equals(this.mergeable, pullRequest.mergeable) &&
        Objects.equals(this.merged, pullRequest.merged) &&
        Objects.equals(this.mergedAt, pullRequest.mergedAt) &&
        Objects.equals(this.mergedBy, pullRequest.mergedBy) &&
        Objects.equals(this.milestone, pullRequest.milestone) &&
        Objects.equals(this.number, pullRequest.number) &&
        Objects.equals(this.patchUrl, pullRequest.patchUrl) &&
        Objects.equals(this.pinOrder, pullRequest.pinOrder) &&
        Objects.equals(this.requestedReviewers, pullRequest.requestedReviewers) &&
        Objects.equals(this.requestedReviewersTeams, pullRequest.requestedReviewersTeams) &&
        Objects.equals(this.reviewComments, pullRequest.reviewComments) &&
        Objects.equals(this.state, pullRequest.state) &&
        Objects.equals(this.title, pullRequest.title) &&
        Objects.equals(this.updatedAt, pullRequest.updatedAt) &&
        Objects.equals(this.url, pullRequest.url) &&
        Objects.equals(this.user, pullRequest.user);
  }

  @Override
  public int hashCode() {
    return Objects.hash(additions, allowMaintainerEdit, assignee, assignees, base, body, changedFiles, closedAt, comments, createdAt, deletions, diffUrl, draft, dueDate, head, htmlUrl, id, isLocked, labels, mergeBase, mergeCommitSha, mergeable, merged, mergedAt, mergedBy, milestone, number, patchUrl, pinOrder, requestedReviewers, requestedReviewersTeams, reviewComments, state, title, updatedAt, url, user);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PullRequest {\n");
    
    sb.append("    additions: ").append(toIndentedString(additions)).append("\n");
    sb.append("    allowMaintainerEdit: ").append(toIndentedString(allowMaintainerEdit)).append("\n");
    sb.append("    assignee: ").append(toIndentedString(assignee)).append("\n");
    sb.append("    assignees: ").append(toIndentedString(assignees)).append("\n");
    sb.append("    base: ").append(toIndentedString(base)).append("\n");
    sb.append("    body: ").append(toIndentedString(body)).append("\n");
    sb.append("    changedFiles: ").append(toIndentedString(changedFiles)).append("\n");
    sb.append("    closedAt: ").append(toIndentedString(closedAt)).append("\n");
    sb.append("    comments: ").append(toIndentedString(comments)).append("\n");
    sb.append("    createdAt: ").append(toIndentedString(createdAt)).append("\n");
    sb.append("    deletions: ").append(toIndentedString(deletions)).append("\n");
    sb.append("    diffUrl: ").append(toIndentedString(diffUrl)).append("\n");
    sb.append("    draft: ").append(toIndentedString(draft)).append("\n");
    sb.append("    dueDate: ").append(toIndentedString(dueDate)).append("\n");
    sb.append("    head: ").append(toIndentedString(head)).append("\n");
    sb.append("    htmlUrl: ").append(toIndentedString(htmlUrl)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    isLocked: ").append(toIndentedString(isLocked)).append("\n");
    sb.append("    labels: ").append(toIndentedString(labels)).append("\n");
    sb.append("    mergeBase: ").append(toIndentedString(mergeBase)).append("\n");
    sb.append("    mergeCommitSha: ").append(toIndentedString(mergeCommitSha)).append("\n");
    sb.append("    mergeable: ").append(toIndentedString(mergeable)).append("\n");
    sb.append("    merged: ").append(toIndentedString(merged)).append("\n");
    sb.append("    mergedAt: ").append(toIndentedString(mergedAt)).append("\n");
    sb.append("    mergedBy: ").append(toIndentedString(mergedBy)).append("\n");
    sb.append("    milestone: ").append(toIndentedString(milestone)).append("\n");
    sb.append("    number: ").append(toIndentedString(number)).append("\n");
    sb.append("    patchUrl: ").append(toIndentedString(patchUrl)).append("\n");
    sb.append("    pinOrder: ").append(toIndentedString(pinOrder)).append("\n");
    sb.append("    requestedReviewers: ").append(toIndentedString(requestedReviewers)).append("\n");
    sb.append("    requestedReviewersTeams: ").append(toIndentedString(requestedReviewersTeams)).append("\n");
    sb.append("    reviewComments: ").append(toIndentedString(reviewComments)).append("\n");
    sb.append("    state: ").append(toIndentedString(state)).append("\n");
    sb.append("    title: ").append(toIndentedString(title)).append("\n");
    sb.append("    updatedAt: ").append(toIndentedString(updatedAt)).append("\n");
    sb.append("    url: ").append(toIndentedString(url)).append("\n");
    sb.append("    user: ").append(toIndentedString(user)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

