/*
 * Gitea API
 * This documentation describes the Gitea API.
 *
 * OpenAPI spec version: 1.27.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.gitea.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.gitea.model.PullRequestMinimalHead;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * PullRequestMinimal is the minimal information about a pull request, as returned in the &#x60;pull_requests&#x60; field of a workflow run.
 */
@ApiModel(description = "PullRequestMinimal is the minimal information about a pull request, as returned in the `pull_requests` field of a workflow run.")

public class PullRequestMinimal {
  @SerializedName("base")
  private PullRequestMinimalHead base = null;

  @SerializedName("head")
  private PullRequestMinimalHead head = null;

  @SerializedName("id")
  private Long id = null;

  @SerializedName("number")
  private Long number = null;

  @SerializedName("url")
  private String url = null;

  public PullRequestMinimal base(PullRequestMinimalHead base) {
    this.base = base;
    return this;
  }

   /**
   * Get base
   * @return base
  **/
  @ApiModelProperty(value = "")
  public PullRequestMinimalHead getBase() {
    return base;
  }

  public void setBase(PullRequestMinimalHead base) {
    this.base = base;
  }

  public PullRequestMinimal head(PullRequestMinimalHead head) {
    this.head = head;
    return this;
  }

   /**
   * Get head
   * @return head
  **/
  @ApiModelProperty(value = "")
  public PullRequestMinimalHead getHead() {
    return head;
  }

  public void setHead(PullRequestMinimalHead head) {
    this.head = head;
  }

  public PullRequestMinimal id(Long id) {
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @ApiModelProperty(value = "")
  public Long getId() {
    return id;
  }

  public void setId(Long id) {
    this.id = id;
  }

  public PullRequestMinimal number(Long number) {
    this.number = number;
    return this;
  }

   /**
   * Get number
   * @return number
  **/
  @ApiModelProperty(value = "")
  public Long getNumber() {
    return number;
  }

  public void setNumber(Long number) {
    this.number = number;
  }

  public PullRequestMinimal url(String url) {
    this.url = url;
    return this;
  }

   /**
   * Get url
   * @return url
  **/
  @ApiModelProperty(value = "")
  public String getUrl() {
    return url;
  }

  public void setUrl(String url) {
    this.url = url;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PullRequestMinimal pullRequestMinimal = (PullRequestMinimal) o;
    return Objects.equals(this.base, pullRequestMinimal.base) &&
        Objects.equals(this.head, pullRequestMinimal.head) &&
        Objects.equals(this.id, pullRequestMinimal.id) &&
        Objects.equals(this.number, pullRequestMinimal.number) &&
        Objects.equals(this.url, pullRequestMinimal.url);
  }

  @Override
  public int hashCode() {
    return Objects.hash(base, head, id, number, url);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PullRequestMinimal {\n");
    
    sb.append("    base: ").append(toIndentedString(base)).append("\n");
    sb.append("    head: ").append(toIndentedString(head)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    number: ").append(toIndentedString(number)).append("\n");
    sb.append("    url: ").append(toIndentedString(url)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

