/*
 * Gitea API
 * This documentation describes the Gitea API.
 *
 * OpenAPI spec version: 1.27.3
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.gitea.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.gitea.model.PullRequestMinimalHeadRepo;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * PullRequestMinimalHead
 */

public class PullRequestMinimalHead {
  @SerializedName("ref")
  private String ref = null;

  @SerializedName("repo")
  private PullRequestMinimalHeadRepo repo = null;

  @SerializedName("sha")
  private String sha = null;

  public PullRequestMinimalHead ref(String ref) {
    this.ref = ref;
    return this;
  }

   /**
   * Get ref
   * @return ref
  **/
  @ApiModelProperty(value = "")
  public String getRef() {
    return ref;
  }

  public void setRef(String ref) {
    this.ref = ref;
  }

  public PullRequestMinimalHead repo(PullRequestMinimalHeadRepo repo) {
    this.repo = repo;
    return this;
  }

   /**
   * Get repo
   * @return repo
  **/
  @ApiModelProperty(value = "")
  public PullRequestMinimalHeadRepo getRepo() {
    return repo;
  }

  public void setRepo(PullRequestMinimalHeadRepo repo) {
    this.repo = repo;
  }

  public PullRequestMinimalHead sha(String sha) {
    this.sha = sha;
    return this;
  }

   /**
   * Get sha
   * @return sha
  **/
  @ApiModelProperty(value = "")
  public String getSha() {
    return sha;
  }

  public void setSha(String sha) {
    this.sha = sha;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PullRequestMinimalHead pullRequestMinimalHead = (PullRequestMinimalHead) o;
    return Objects.equals(this.ref, pullRequestMinimalHead.ref) &&
        Objects.equals(this.repo, pullRequestMinimalHead.repo) &&
        Objects.equals(this.sha, pullRequestMinimalHead.sha);
  }

  @Override
  public int hashCode() {
    return Objects.hash(ref, repo, sha);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PullRequestMinimalHead {\n");
    
    sb.append("    ref: ").append(toIndentedString(ref)).append("\n");
    sb.append("    repo: ").append(toIndentedString(repo)).append("\n");
    sb.append("    sha: ").append(toIndentedString(sha)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

